### ISSUE TITLE
请问@specail如何使用，能否给个例子

### ISSUE THREAD

**Issue by 0kai** [wysaid/android-gpuimage-plus#10]
> special方法参数解释: @special方法格式为 "@special <N>" 其中参数<N> 为该特效的编号。 此类用于处理所有不具备通用性的特效。直接重新编写一个processor以解决。

这个编号是指的 GLES20.glCreateProgram() 吗？
我试过，但是不行。
`specialParser - unresolved index: 12
特效指令 "@special 12" 无法生成任何特效!`

望回复，谢谢！

**Comment by wysaid** [comment]
不是的， 这个是某些不能通过配置文件实现的特效的单独实现接口， 现在已经废弃了， 请更新一下， 做出了相关修改

**Comment by 0kai** [comment]
好吧，不能自定义。
自己搞了一套了。
