### ISSUE TITLE
May you make the gpuimage-plus 100% Open Source

### ISSUE THREAD

**Issue by enkhtogtokh** [wysaid/android-gpuimage-plus#106]
Dear Wysaid,

If you remember, i had a some request on mips arch. I very like to use the android-gpuimage-plus.
But now i need the mips64 arch. And once i need this type of things, i only need to contact with you. Because i could not compile it in this case, you know this.  

May you make your project 100% open source ?  
Thank you.

Sincerely,
Developer

**Comment by wysaid** [comment]
Yes,  in May.

**Comment by enkhtogtokh** [comment]
Dear Wysaid,

That will be really great. Thank you very much. If there is anything, i will be happy to contribute with your awesome project. Happy to see that soon.

Sincerely,
Developer

**Comment by wysaid** [comment]
😋

**Comment by wysaid** [comment]
It's already 100% open source with the MIT License.

**Comment by enkhtogtokh** [comment]
Dear Wysaid,

It is really great. Thank you very much.
