### ISSUE TITLE
请问滤镜可以叠加吗？

### ISSUE THREAD

**Issue by roger66** [wysaid/android-gpuimage-plus#115]
比如亮度饱和度对比度三个一起修改

**Comment by wysaid** [comment]
三个串起来就行。建议看看项目首页提供的编辑工具， 可以生成你想要的滤镜

**Comment by roger66** [comment]
感谢你的回复，项目中的需求是三个进度条，分别改变亮度，饱和度，对比度，然后叠加在一起

**Comment by wysaid** [comment]
你需要自己用c++写一个滤镜包含这三者， 参考demo里面封装的c++滤镜的demo

使用 CGENativeLibrary 里面的 cgeCreateCustomNativeFilter 创建并使用

你先试试看吧， 如果有什么不明白的地方再告诉我

**Comment by roger66** [comment]
那就是现在的版本不支持叠加咯，C++我完全不懂，项目还是很牛逼的，谢谢你了

**Comment by wysaid** [comment]
也是支持的

**Comment by wysaid** [comment]
我这几天稍微改一下吧， 这个功能确实比较有必要的

**Comment by roger66** [comment]
感谢感谢

**Comment by roger66** [comment]
@wysaid 视频滤镜离屏渲染可以知道进度吗？

**Comment by bookzhan** [comment]
@roger66 自己写jni回调就好了，源码已经放出来了

**Comment by roger66** [comment]
在哪个地方改？我刚接触不是很懂

**Comment by bookzhan** [comment]
@roger66 在cgeVideoUtils.cpp 里面有一个while(1)在这里面写回调就好了,然后把时间戳转换成秒回调就可以了

**Comment by roger66** [comment]
好的，CGEImageHandler可以独立使用吗？因为多个ImageGLSurfaceView嵌套在RecyclerView里滑动会卡顿？

**Comment by roger66** [comment]
@bookzhan 您好，C++部分我看不懂，能把代码贴出来学习一下吗？

**Comment by bookzhan** [comment]
@roger66 具体实现我也没写,只是知道在这里可以回调进度

**Comment by roger66** [comment]
@bookzhan 有空能帮忙写一下吗？我实在不懂，谢谢

**Comment by XuanLiuNB** [comment]
@wysaid 你好，请问多个滤镜组合的功能现在项目里面支持吗？

**Comment by wysaid** [comment]
支持

**Comment by XuanLiuNB** [comment]
@wysaid 谢谢回复  是想在录制视频的时候动态使用组合滤镜  没有看到相关的代码  可以提示一下吗  感激不尽

**Comment by XuanLiuNB** [comment]
@wysaid 知道怎么设置了  谢谢

**Comment by coderlin** [comment]
@XuanLiuNB 请问在哪设置组合滤镜呢？
