### ISSUE TITLE
怎样将录制的视频方向旋转

### ISSUE THREAD

**Issue by candrwow** [wysaid/android-gpuimage-plus#118]
用户横向摆放手机拍的视频我想旋转，应该怎么设置呢，set*Rotation三个方法只是改变了预览GLSurfaceView的显示，并没有改变最后保存的视频方向

**Comment by wysaid** [comment]
这一块代码都在， 你可以自己完成一下。 给视频文件写入旋转信息即可

**Comment by candrwow** [comment]
抱歉，我对视频学习不太深入，这个视频文件写入旋转信息是有什么方法吗，用ffmpeg还是java原生，我这边用ffmpeg旋转6秒的1080视频大概要用7，8秒，有1，2秒左右的方案吗

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/issues/79

**Comment by candrwow** [comment]
谢谢哈，我在网上找到一个ffmpeg的命令取代之前的transport命令，速度已经满足我的要求了。
String command = "-i " + file + " -c copy -metadata:s:v:0 rotate=90 " + ImageUtil.getPath() + "/rec_ChangeOrientation.mp4";

**Comment by dasamanren** [comment]
@candrwow 这个命令写在哪里,我也有这个需求

**Comment by dasamanren** [comment]
横屏拍摄的视频旋转之后加完水印生成的最终视频,方向又转回来了,需要准备一张横着的水印再旋转一次~~~
