### ISSUE TITLE
CameraRecordGLSurfaceView显示不出画面

### ISSUE THREAD

**Issue by WooYu** [wysaid/android-gpuimage-plus#124]
如果有两个activity，都有CameraRecordGLSurfaceView。但是从第一个跳转到第二个activity时，第二个activity中的CameraRecordGLSurfaceView显示不出画面。是因为第一个activity中的CameraRecordGLSurfaceView没释放吗？

**Comment by WooYu** [comment]
#116 和这个是同样的问题。在onPause（）中我已经释放资源了。在CameraDemoActivity再打开一次CameraDemoActivity就可以看到问题了

**Comment by wysaid** [comment]
现在整个项目都开源了哈， 这个问题你先调试下看看吧。
后续我会看看你说的这个应用场景

**Comment by WooYu** [comment]
debug过 了，没发现问题。看日志创建和录制的回调都走成功，没有错误日志，现在没有思路解决这个问题
