### ISSUE TITLE
本地视频添加滤镜后怎么保存？

### ISSUE THREAD

**Issue by gailgou** [wysaid/android-gpuimage-plus#13]
我看到实时视频添加滤镜后可以录像并保存，但是其它的本地视频或者网络流应该怎样保存呢？

**Comment by wysaid** [comment]
Not supported by now, waiting for my later commits~😊

**Comment by gailgou** [comment]
哈哈，那等着看后面的呀，还有jni能开放吗，非常想研究研究

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/tree/e59049a30c0af0dd7ea5db269ed7d332459d2c99

**Comment by gailgou** [comment]
thanks.

**Comment by jsjjkfc** [comment]
大牛，我不懂ndk层的开发，不过你这项目拉下来我的AS一直在building咋回事。。。

**Comment by wysaid** [comment]
@jsjjkfc 自行解决哦， 网络或者项目配置问题

**Comment by wysaid** [comment]
supported by now

**Comment by wanghaibao123** [comment]
一直没有找到这方法啊
