### ISSUE TITLE
滤镜状态如何保存？

### ISSUE THREAD

**Issue by Hellozhongxin** [wysaid/android-gpuimage-plus#130]
在Activity中设置了CameraRecordGLSurfaceView的滤镜，然后切到其他界面，再回去Activity,滤镜效果消失了。即使重新setFilterWithConfig（）设置相应的滤镜，也无效，请问这是为什么？
CameraRecordGLSurfaceView的初始化放在onCreate(),
    protected void onResume()
    {
        super.onResume();
        mSurfaceView.onResume();
        ToastUtil.show("isBeautyMode:" + isBeautyMode);
        if (isBeautyMode) {
            if (mSurfaceView != null)
                mSurfaceView.setFilterWithConfig(effectConfigs[18]);
        }
    }

    @Override
    protected void onPause()
    {
        super.onPause();
        CameraInstance.getInstance().stopCamera();
       mSurfaceView.release(null);
        mSurfaceView.onPause();
    }

**Comment by wysaid** [comment]
>mSurfaceView.setFilterWithConfig(effectConfigs[18]);
这一句写到 setOnCreateCallback 里面

**Comment by Hellozhongxin** [comment]
好的 👌 🙏谢谢
