### ISSUE TITLE
Ffmpeg 版本

### ISSUE THREAD

**Issue by gzgang** [wysaid/android-gpuimage-plus#138]
请问你用的 Ffmpeg 版本是多少呢，我用 3.3.2 编译出来的 libffmpeg.so 来替换你的 libffmpeg.so; 会出错，提示 undefined reference to 'avcodec_alloc_frame； 然后我看 ffmpeg 3.3.2 的 avcodec.h 文件里面没有 'avcodec_alloc_frame' 的定义。

另外能否提供下你的 ffmpeg 编译脚本呢。

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/issues/93

**Comment by gzgang** [comment]
谢谢大师兄，这个问题解决了：）

**Comment by fatCat2015** [comment]
@gzgang   大兄弟 怎么解决的啊
