### ISSUE TITLE
Start recording failed

### ISSUE THREAD

**Issue by Hellozhongxin** [wysaid/android-gpuimage-plus#139]
mSurfaceView.startRecording(recordFilename, new CameraRecordGLSurfaceView.StartRecordingCallback() {
                @Override
                public void startRecordingOver(boolean success)
                {
                    if (success) {
                 ToastUtil.show("Start recording OK");
                    } else {
                 ToastUtil.show("Start recording failed");
                    }
                }
            });
请问在录制的时候，为什么视频是正常录制的，但是会提示 "Start recording failed"？

**Comment by wysaid** [comment]
显然不可能， 显示如此提示的时候， 音频线程根本不会启动。建议你参考一下代码

**Comment by Hellozhongxin** [comment]
嗯 确实，音频是没有录制成功，只录制了视频。请问可能是什么原因，影响了音频线程的开启？

**Comment by wysaid** [comment]
这个……你能否debug一下？ 我没遇到过这种情况， 照理说不应该出现的。
或者你把出问题时tag为 “libCGE”和 “wysaid”的日志贴一下

**Comment by Hellozhongxin** [comment]
找到原因了。因为在录制的时候这百年开启了语音识别的功能。所以……。Thanks!

**Comment by Hellozhongxin** [comment]
请问，录制音频和语音识别能共存吗？现在的开了语音识别，录制的视频就没有声音了。

**Comment by wysaid** [comment]
这块代码都在， 显然是你的麦克风只能被单例占用。
你把语音识别跟录视频结合起来， 录视频的时候从语音识别里面拿麦克风数据吧
