### ISSUE TITLE
滤镜如何更改贴图的坐标？

### ISSUE THREAD

**Issue by liuxingfy** [wysaid/android-gpuimage-plus#14]

**Comment by wysaid** [comment]
这个暂时没有哦， 你想要的是什么样的功能， 如果实现不复杂我可以考虑加进去

**Comment by wysaid** [comment]
当然你们也可以用自己的办法解决， 比如设计一张全屏图， 把自己的贴图贴好， 然后再使用进去。
不过这个办法比较曲折， 而且浪费内存。 
我会考虑后面版本加入类似功能的

**Comment by liuxingfy** [comment]
你好，是类似FaceU的帧动画功能，需要图片切换和变化位置

**Comment by wysaid** [comment]
@liuxingfy 
你好， 这种功能不应该跑滤镜啦， 你可以看看那个 TextureRenderer
应该用这种方式来做， 最好的方法是你自己扩展， 写一个类似 Sprite 的东西， 实时控制对纹理进行旋转缩放平移(传入人脸关键点数据什么的

**Comment by wysaid** [comment]
你只要绑定那个 FrameRecorder 的 framebuffer, 往里面绘制， 录制开始之后会自动将你绘制的内容录制到视频里面的

**Comment by liuxingfy** [comment]
@wysaid 你好，我写了一个基于TextureRendererDrawOrigin的AnimRenderer，在CameraGLSurfaceView的onDrawFrame函数里绘制时，发现放在 GLES20.glBindFramebuffer(GLES20.GL_FRAMEBUFFER, 0); 前后的效果不同(坐标，缩放，翻转)， 不知道FrameRecorder 的framebuffer里做了什么操作？我如何让录制进去的效果和预览的效果保持一致？

**Comment by wysaid** [comment]
mater分支最新版本(20dc490)下 CameraGLSurfaceView 第601行， 在 update和 runProc之间绘制
绘制之前加上  mFrameRecorder.bindImageFBO();
使用我内建的framebuffer
