### ISSUE TITLE
win10 平台Android stdio 可以直接编译JNI层代码么？

### ISSUE THREAD

**Issue by 598588152** [wysaid/android-gpuimage-plus#141]
win10 平台Android stdio 可以直接编译JNI层代码么？

**Comment by wysaid** [comment]
没试过， 但是 cygwin 肯定是可以的， 你自己配置一下， 写一下makefile不用cygwin应该也行

**Comment by 598588152** [comment]
恩， 谢了

**Comment by 598588152** [comment]
LOCAL_SRC_FILES :=  \
			$(TRACKER_SOURCE)/CLM.cpp \
			$(TRACKER_SOURCE)/FDet.cpp \
			$(TRACKER_SOURCE)/PAW.cpp \
			$(TRACKER_SOURCE)/Patch.cpp \
			$(TRACKER_SOURCE)/FCheck.cpp \
			$(TRACKER_SOURCE)/IO.cpp \
			$(TRACKER_SOURCE)/PDM.cpp \
			$(TRACKER_SOURCE)/Tracker.cpp \
			\
            $(TRACKER_ROOT)/cgeFaceTracker.cpp \
			$(TRACKER_ROOT)/cgeFaceTrackerWrapper.cpp \


这段代码编译不[armeabi] SharedLibrary  : libCGEExt.so
[armeabi] Install        : libCGEExt.so => libs/armeabi/libCGEExt.so
[armeabi] Compile++ arm  : FaceTracker <= CLM.cpp
[armeabi] Compile++ arm  : FaceTracker <= FDet.cpp
[armeabi] Compile++ arm  : FaceTracker <= PAW.cpp
[armeabi] Compile++ arm  : FaceTracker <= Patch.cpp
[armeabi] Compile++ arm  : FaceTracker <= FCheck.cpp
error: error opening 'C:/Users/lihy/Desktop/voidrecoder/new/android-gpuimage-plus-master/library/src/main/obj/local/armeabi/objs/FaceTracker/C_/Users/lihy/Desktop/voidrecoder/new/android-gpuimage-plus-master/library/src/main/jni/faceTracker/jni/__/FaceTracker/FCheck.o.d': No such file or directory
1 error generated.
make: *** [C:/Users/lihy/Desktop/voidrecoder/new/android-gpuimage-plus-master/library/src/main/obj/local/armeabi/objs/FaceTracker/C_/Users/lihy/Desktop/voidrecoder/new/android-gpuimage-plus-master/library/src/main/jni/faceTracker/jni/__/FaceTracker/FCheck.o] Error 1
过，可以看下吗？

**Comment by 598588152** [comment]
刚编译通过了，路径不对，改了下路径，就ok了。
我想改下音频的设置，采样率为48000，通道数为2，立体声，可以提示下吗，发现 
switch ((*codec)->type) {
    case AVMEDIA_TYPE_AUDIO:
        c->sample_fmt  = AV_SAMPLE_FMT_FLTP;
        c->bit_rate    = 64000;
        c->sample_rate = audioSampleRate;
        c->channels    = 2;//1
        c->flags      |= CODEC_FLAG_GLOBAL_HEADER;
        c->strict_std_compliance = -2;
        break;
在这里面改 跑代码 直接崩掉了

**Comment by wysaid** [comment]
这个不能光改这里， 还有java层传入数据， 也需要改。 你看看相关代码吧~

**Comment by 598588152** [comment]
private static final int sampleRate = 48000;//48000 44100
        ByteBuffer audioBufferRef;
        ShortBuffer audioBuffer;
        StartRecordingCallback recordingCallback;

        private AudioRecordRunnable(StartRecordingCallback callback) {
            recordingCallback = callback;
            try {//CHANNEL_IN_MONO
                bufferSize = AudioRecord.getMinBufferSize(sampleRate,
                        AudioFormat.CHANNEL_IN_STEREO, AudioFormat.ENCODING_PCM_16BIT);
                Log.i(LOG_TAG, "audio min buffer size: " + bufferSize);
                audioRecord = new AudioRecord(MediaRecorder.AudioSource.MIC, sampleRate,
                        AudioFormat.CHANNEL_IN_STEREO, AudioFormat.ENCODING_PCM_16BIT, bufferSize);
                //                audioData = new short[bufferSize];//
                audioBufferRef = ByteBuffer.allocateDirect(bufferSize * 2).order(ByteOrder.nativeOrder());
                audioBuffer = audioBufferRef.asShortBuffer();
            } catch (Exception e) {
                if (audioRecord != null) {
                    audioRecord.release();
                    audioRecord = null;
                }
            }
java层也设置了，可是还会闪退掉，可以给点提示么，这代码，我也刚看不久，麻烦了

**Comment by wysaid** [comment]
[这个地方的采样率44100改了没](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/interface/cgeVideoEncoder.cpp#L43)
类似的细节你好好理一下。
录像这个demo来自官方的 [muxing.c](https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/muxing.c)
建议参照这个demo， 先把逻辑理顺一下。
然后我这边使用的ffmpeg版本不是官网最新的， 你理一下流程就行， 如果不想更新ffmpeg版本， ffmpeg接口最好还是按我这边的版本来写

**Comment by 598588152** [comment]
static AVStream *addStream(AVFormatContext *oc, AVCodec **codec,
                            enum AVCodecID codec_id, int frameRate, int width = -1, int height = -1, int bitRate = 1650000, int audioSampleRate = 48000)

改了
恩，好

**Comment by suchengjian** [comment]
@598588152 修改音频采样率改好了吗，我这按照上边改的还是闪退，能告诉我怎么改么？
