### ISSUE TITLE
Is there a way to change filter values (not intensity)

### ISSUE THREAD

**Issue by NiekAkerboom** [wysaid/android-gpuimage-plus#142]
Lets say I have the following filter applied:
`@adjust shadowhighlight -200 200`
Or
`@adjust lut edgy_amber.png`

Is it possible to change the actual filter values like "-200", "200" and "edgy_amber.png" in the same way you can change the intensity of the said filters without recreating them?

**Comment by wysaid** [comment]
For ``@adjust shadowhighlight -200 200``
You can certainly do that.  But you should write your own function to fetch the filter with it's real type [CGEShadowHighlightFilter](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/include/filters/cgeShadowHighlightAdjust.h#L16),
and call the function ``setShadow `` and ``setHighlight ``

**Comment by NiekAkerboom** [comment]
Thanks, I'll go through that today.

**Comment by wysaid** [comment]
For ``@adjust lut edgy_amber.png``
You can do it, too.
Fetch the filter from the handler, and cast it to [CGELookupFilter](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/include/filters/cgeLookupFilter.h#L16) as a variable ``lookupFilter``

```
GLuint newTex = someFunctionToGenerateTexFromBitmap(yourBitmap);
auto lastTex = lookupFilter->lookupTexture();
glDeleteTextures(1, &lastTex);
lookupFilter->setLookupTexture(newTex);
```

**Comment by wysaid** [comment]
@NiekAkerboom 
By the way, please make sure these functions are called in the GL thread.

**Comment by oblivion0001** [comment]
it is two da shen chatting ,I can't stand ;
