### ISSUE TITLE
add blur to half screen

### ISSUE THREAD

**Issue by storewaladotcom** [wysaid/android-gpuimage-plus#156]
How can i go about adding a blur to only top half of the screen while the bottom half previews normally. I would like to record the video with the top half blur in place as well. Can i do this via a custom filter? or this has to be done in the onDrawFrame method?

**Comment by wysaid** [comment]
You can write a custom filter.

**Comment by storewaladotcom** [comment]
Would you be kind enough to direct me on how to write the custom filter in Java? If there is a sample I will follow it. 

Or if you can tell me the pseudo code for such a filter, that will help.

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/tree/master/library/src/main/jni/source

See this

**Comment by storewaladotcom** [comment]
thank you! would you be kind enough to provide the pseudocode for the filter that will blur only half of the screen?

**Comment by storewaladotcom** [comment]
i'll be able to figure it out! Appreciate you building this awesome repo. May god bless!
