### ISSUE TITLE
可不可以添加一个获取滤镜处理之后YUV数据的方法。

### ISSUE THREAD

**Issue by WooYu** [wysaid/android-gpuimage-plus#157]

**Comment by wysaid** [comment]
事情太多了， 这一类的需求你自己加一下吧， 在录制的模块， enccoder 里面会有一步得到滤镜之后的yuv数据， 自己加一个回调就好了

**Comment by WooYu** [comment]
![image](https://user-images.githubusercontent.com/10032892/27960816-3fc5c066-635f-11e7-8bd3-aea64b3b5a0b.png)
"sh"在windows中代表什么 。我现在用ndk-build编译的so使用时报错了

![image](https://user-images.githubusercontent.com/10032892/27960888-801a1dc4-635f-11e7-9498-3be07c051064.png)

**Comment by wysaid** [comment]
win下用 cygwin 编译

**Comment by WooYu** [comment]
![image](https://user-images.githubusercontent.com/10032892/28313389-4679bd26-6be9-11e7-9d16-3c1b1d074901.png)
![image](https://user-images.githubusercontent.com/10032892/28313430-64cc4014-6be9-11e7-9bcd-7654dabdb67d.png)
为什么编译出来的so文件这么大

**Comment by wysaid** [comment]
看 path/of/jni/libs 目录下的
