### ISSUE TITLE
Change ImageGLSurfaceView Background Color

### ISSUE THREAD

**Issue by nayankukadiya** [wysaid/android-gpuimage-plus#165]
I want to change ImageGLSurfaceView background color which is always black, So i changed value in

GLES20.glClearColor(32.0f, 32.0f, 32.0f, 255.0f);

but then it takes white color not same as rgba code.

**Comment by wysaid** [comment]
range: [0, 1]

**Comment by nayankukadiya** [comment]
Yes It's work. Thanks a lot.
