### ISSUE TITLE
jni 可否开源? 是否可以将ffmpeg的 依赖剥离, 同时提供其它架构的so文件

### ISSUE THREAD

**Issue by nervending** [wysaid/android-gpuimage-plus#17]
如题
jni如果不方便开源的话, 可否将ffmpeg的依赖剥离下来, 否则只有滤镜功能还要带上ffmpeg, 包增加比较大
还有一点是希望将打包出来的所有so都提供出来, 这样方便使用
非常感谢作者

**Comment by nervending** [comment]
看了历史的jni代码, 可是后面应该有很多新的修改

**Comment by wysaid** [comment]
repo下有一个 with_no_ffmpeg 分支， 提供了所有的架构版本， 并且不包含ffmpeg

**Comment by nervending** [comment]
好的 多谢
