### ISSUE TITLE
Update documentation for LUT usage

### ISSUE THREAD

**Issue by vxhviet** [wysaid/android-gpuimage-plus#171]
Pardon me if I'm wrong but in your [documentation ](https://github.com/wysaid/android-gpuimage-plus/wiki/Parsing-String-Rule-En#adjust-format-adjust-function-arg1argn)for applying LUT it says:

```
lut: (tips: lookup table)
  Param num 1 (lookup table resource name)

  e.g. "@lookup lookup.png" 
```

But in your demo, you use it as:

`@adjust lut your_file.png` 

and this is indeed working fine, so I guess the doc need a little update.

**Comment by wysaid** [comment]
Aha, it's just an example~
You may put lots of lookup images(certainly with different names)

**Comment by vxhviet** [comment]
I mean the key work is different `@adjust lut` instead of `@lookup` . But anyway, it's working fine now, thank you a lot.

**Comment by wysaid** [comment]
Oooooops……
I know what you say, and I fixed it. Thanks a lot.
