### ISSUE TITLE
[Question] Best way to apply filter to image without a Surface?

### ISSUE THREAD

**Issue by vxhviet** [wysaid/android-gpuimage-plus#174]
Hi @wysaid , I have a small question to ask:

In your `ImageGLSurfaceView` I see you have a underlying `CGEImageHandler` to manage the filter, finkd of like what [`GPUImage`](https://github.com/CyberAgent/android-gpuimage/blob/master/library/src/jp/co/cyberagent/android/gpuimage/GPUImage.java) does to [`GPUImageView`](https://github.com/CyberAgent/android-gpuimage/blob/master/library/src/jp/co/cyberagent/android/gpuimage/GPUImageView.java).

In your tutorial, however I can see you have a very simple 1 liner like this to retrieve the filtered image:

`Bitmap dstImage = CGENativeLibrary.filterImage_MultipleEffects(src, ruleString, 1.0f);`

My use case is quite simple. I have a list of thumbnail image that I need to apply a list of LUT filters to, so that they can be used as preview. As thus I don't really need the surface view. With such use case, is using `CGEImageHandler` or `CGENativeLibrary.filterImage_MultipleEffects(src, ruleString, 1.0f)` a better option?

**Comment by wysaid** [comment]
It's better to use ``CGEImageHandler``, [See this](https://github.com/wysaid/android-gpuimage-plus/blob/master/cgeDemo/src/main/java/org/wysaid/cgeDemo/TestCaseActivity.java#L156)

**Comment by vxhviet** [comment]
Thanks a lot for your prompt response, you're awesome as always. :)

**Comment by vxhviet** [comment]
Hey, just want to chimp in a little bit. Regarding your example, one should not call 

[`handler.processFilters();`](https://github.com/wysaid/android-gpuimage-plus/blob/master/cgeDemo/src/main/java/org/wysaid/cgeDemo/TestCaseActivity.java#L163) 

right after a call to `handler.setFilterWithConfig(filterConfig);` as by default this one has already call `processFilters()`. This bug is either double or reverse an effect depending on which type of LUT is used.

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/java/org/wysaid/nativePort/CGEImageHandler.java#L61
The complete prototype of the `setFilterWithConfig` is
```
    //config: The filter rule string. Pass null for config to clear all filters.
    //shouldClearOlder: The last filter will be cleared if it's true.
    //    There may be memory leaks if you pass false for 'shouldClearOlder' when you don't clear it by yourself.
    //shouldProcess: This marks if the filter should be run right now.
    //    The result will not change if you pass false for 'shouldProcess' until you call 'processFilters'.
    public void setFilterWithConfig(String config, boolean shouldClearOlder, boolean shouldProcess) {
        nativeSetFilterWithConfig(mNativeAddress, config, shouldClearOlder, shouldProcess);
    }
```
So you can pass false for the last arg.

**Comment by vxhviet** [comment]
Yes, this is what help me to figure out the problem as I follow very closely your provided example but my preview LUT panel just look kind of wrong (some look like it has been applied multiple time, the inverse LUT filter looks normally which indicate the filter has been applied twice).
