### ISSUE TITLE
[ERROR] call to OpenGL ES API with no current context (logged once per thread)

### ISSUE THREAD

**Issue by vxhviet** [wysaid/android-gpuimage-plus#175]
## Use case
I have experienced a strange crash recently and after a lot of investigation I've narrow down the issue to this. 

My use case is very simple, I'm trying to down sample a large image before loading it into `ImageGLSurfaceView` via two utility class [`BitmapLoadUtils` ](https://github.com/Yalantis/uCrop/blob/master/ucrop/src/main/java/com/yalantis/ucrop/util/BitmapLoadUtils.java) and [`BitmapLoadTask`](https://github.com/Yalantis/uCrop/blob/master/ucrop/src/main/java/com/yalantis/ucrop/task/BitmapLoadTask.java). 

These two classes is pulling from another library but after some investigation I cannot understand how can it affect this library in anyway (one method is just to calculate the desired `Bitmap` size, another method is an `AsyncTask` that will decode said image in background **but** the result is returned in main thread).

Every time the app will crash with this stack trace:

```
I/wysaid: ImageGLSurfaceView Construct...
I/wysaid: View port: 0, 0, 0, 0
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
I/OpenGLRenderer: Initialized EGL, version 1.4
I/wysaid: ImageGLSurfaceView onSurfaceCreated...
I/libCGE: CGEImageHandlerAndroid created!
D/BitmapLoadUtils: maxBitmapSize: 2078
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
I/wysaid: View port: 0, 366, 936, 0
W/Adreno-EGL: <qeglDrvAPI_eglSwapBuffers:3678>: EGL_BAD_CONTEXT
D/BitmapWorkerTask: Uri scheme: file
W/GLThread: eglSwapBuffers failed: EGL_BAD_CONTEXT
W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
W/IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
I/libCGE: color image :: width is 1440; height is 900; stride is 5760; format is 1;flags is 0
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9e700000 in tid 7773 (GLThread 6174)
```

After some research, I found this [StackOverflow item](https://stackoverflow.com/questions/26985858/gles10-glgetintegerv-returns-0-in-lollipop-only), but I'm not sure if it's really the problem.

## Device
LG Nexus 5, Android Marshmallow 6.0.1

## Step to replicate

- Create a new project.

- Import this library.

- import [Ucrop](https://github.com/Yalantis/uCrop) (just so we can easily access these two Util classes, it can be either general or native version).

- Code:

```
protected static final String BASIC_FILTER_CONFIG = "@adjust contrast 1 @adjust brightness 0 @adjust saturation 1 @adjust exposure 0";

...

mSurfaceView = (ImageGLSurfaceView) findViewById(R.id.surface);
        mSurfaceView.setDisplayMode(ImageGLSurfaceView.DisplayMode.DISPLAY_ASPECT_FIT);

        mSurfaceView.setSurfaceCreatedCallback(new ImageGLSurfaceView.OnSurfaceCreatedCallback() {
            @Override
            public void surfaceCreated() {
               
                int maxSize = BitmapLoadUtils.calculateMaxBitmapSize(MainActivity.this);
                Uri in = Uri.fromFile(new File("/storage/emulated/0/Pictures/test/test1.jpg"));
                Uri out = Uri.fromFile(new File("/storage/emulated/0/Pictures/test/output/test1_out.jpg"));
                BitmapLoadUtils.decodeBitmapInBackground(MainActivity.this, in, out, maxSize, maxSize, new BitmapLoadCallback() {
                    @Override
                    public void onBitmapLoaded(@NonNull Bitmap bitmap, @NonNull ExifInfo exifInfo, @NonNull String imageInputPath, @Nullable String imageOutputPath) {
                        mSurfaceView.setImageBitmap(bitmap);
                        mSurfaceView.setFilterWithConfig(BASIC_FILTER_CONFIG);
                    }

                    @Override
                    public void onFailure(@NonNull Exception bitmapWorkerException) {

                    }
                });
            }
        });
```

**Comment by wysaid** [comment]
Please make a fork with this issue, and I will take a look.😋

**Comment by vxhviet** [comment]
Hey thank you so much for your concern,

You can find all the relevant stuff in the [`TestCrashActivity`](https://github.com/vxhviet/android-gpuimage-plus/blob/master/cgeDemo/src/main/java/org/wysaid/cgeDemo/testcrash/TestCrashActivity.java).

**Comment by vxhviet** [comment]
The above `TestCrashAcitvity`, depended on your exist `library`, only throw a `call to OpenGL ES API with no current context (logged once per thread)`  error (blank screen, no crash) which is not quite different from my test.

So I've decided to create a second test [`TestCrashCGEOnlyActivity`](https://github.com/vxhviet/android-gpuimage-plus/blob/master/testcrash/src/main/java/co/myapplication/testcrash/TestCrashCGEOnlyActivity.java) which is depended on a library build with `CGE` module only. This one crash as expected.

**Comment by wysaid** [comment]
OK

**Comment by wysaid** [comment]
A: ``call to OpenGL ES API with no current context (logged once per thread)``
Your function [BitmapLoadUtils.calculateMaxBitmapSize](https://github.com/vxhviet/android-gpuimage-plus/blob/master/cgeDemo/src/main/java/org/wysaid/cgeDemo/testcrash/TestCrashActivity.java#L59) will change the current GLES context.
To solve it , just change the calling of  [loadImage](https://github.com/vxhviet/android-gpuimage-plus/blob/master/cgeDemo/src/main/java/org/wysaid/cgeDemo/testcrash/TestCrashActivity.java#L48) to 
```
mGLSurfaceView.post(new Runnable() {
    @Override
    public void run() {
        loadImage();
    }
});
```

**Comment by vxhviet** [comment]
Hey thank you for your response. I know it is not a bug of this this repo as I can successfully displayed an Image before. 

Anyway thank you a lot for your time, I'm very appreciated, Really.

**Comment by wysaid** [comment]
🙂
