### ISSUE TITLE
我想把滤镜整合到直播项目里，在拿到纹理id后如何添加滤镜效果呢？

### ISSUE THREAD

**Issue by forgekxf** [wysaid/android-gpuimage-plus#176]

**Comment by wysaid** [comment]
你可以创建一个 TextureDrawer (设为 drawer) 和一个 CGEImageHandler (设为 handler, 加入所需的效果， 使用)

>CGEImageHandler handler = new CGEImageHandler();
>handler.[initWithSize(texWidth, texHeight)](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/java/org/wysaid/nativePort/CGEImageHandler.java#L36);
>handler.[bindTargetFBO()](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/java/org/wysaid/nativePort/CGEImageHandler.java#L90);
>GLES20.glViewport(...)
>drawer.drawTexture(yourTexID);
>handler.processFilters();
>// bind your own FBO, and set to the right viewport
>// call handler.[drawResult()](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/java/org/wysaid/nativePort/CGEImageHandler.java#L89)

大概这样

**Comment by forgekxf** [comment]
出现异常：
[HWA_CAM3]getAFOTP() get vcm otp failed! 
"glDrawArrays" glGetError invalid operation(0x502) at /Users/yangwang/work/git/android-gpuimage-plus/library/src/main/jni/cge/common/cgeImageFilter.cpp:209

**Comment by forgekxf** [comment]
七牛直播自定义filter：
https://developer.qiniu.com/pili/sdk/3719/PLDroidMediaStreaming-function-using#6

**Comment by wysaid** [comment]
弄个fork把有问题的代码简单做个case，可以帮你看看

**Comment by forgekxf** [comment]
https://github.com/forgekxf/android-gpuimage-plus
添加滤镜在 app/src/main/java/com/bhtc/huajuan/push/rtmp/FBO.java，麻烦看一下谢谢

**Comment by wysaid** [comment]
OK, 周一看看

**Comment by forgekxf** [comment]
嗯嗯，今天有时间的话麻烦先看一下，一直没有找到原因呢

**Comment by forgekxf** [comment]
需要把处理过的textureId返回才能渲染出来，如何拿到处理过后的textureId呢？

**Comment by wysaid** [comment]
自己创建

**Comment by forgekxf** [comment]
嗯，现在有时间看一下fork吗

**Comment by wysaid** [comment]
嗯， 再看

**Comment by forgekxf** [comment]
OK多谢

**Comment by wysaid** [comment]
你没说明纹理类型， 如果是 GL_TEXTURE_EXTERNAL_OES 的话， 不能用 TextureDrawer, 要用 TextureRenderer 并且创建的时候标注 isExternalOES为true
你写得比较乱， 并且对于尺寸的处理全是错的， 所以简单重写了一下， 大概下面这样
FBO.java 这样写就行了
```
public class FBO {
    private boolean mEnable = true;
    private int mContentWidth;
    private int mContentHeight;

    private int mOffscreenTexture = 0;
    private FrameBufferObject mFramebuffer;
    private CGEImageHandler mHandler;
    private TextureRendererDrawOrigin drawer;

    public void updateSurfaceSize(int width, int height) {
        if (!mEnable) {
            return;
        }
    }

    public void initialize(Context context) {
        if (!mEnable) {
            return;
        }

        mHandler = new CGEImageHandler();
        drawer = TextureRendererDrawOrigin.create(true);
        mHandler.setFilterWithConfig("@curve RGB(0,255)(255,0) @style cm mapping0.jpg 80 80 8 3");
        mHandler.setFilterIntensity(0.8f);
        mContentWidth = mContentHeight = 0;
        Common.checkGLError("handler create...");
    }

    public void release() {
        if (!mEnable) {
            return;
        }

        if (mHandler != null) {
            mHandler.release();
            mHandler = null;
        }

        if (mFramebuffer != null) {
            mFramebuffer.release();
            mFramebuffer = null;
        }

        if (mOffscreenTexture != 0) {
            Common.deleteTextureID(mOffscreenTexture);
            mOffscreenTexture = 0;
        }
    }

    public int drawFrame(int texId, int texWidth, int texHeight) {
        // 因为没有开启内置美颜，此处纹理类型为 GL_TEXTURE_EXTERNAL_OES
        if (!mEnable) {
            return texId;
        }

        if (mContentWidth != texWidth || mContentHeight != texHeight) {
            mContentWidth = texWidth;
            mContentHeight = texHeight;
            if (mOffscreenTexture != 0) {
                Common.deleteTextureID(mOffscreenTexture);
            }
            mOffscreenTexture = Common.genBlankTextureID(texWidth, texHeight);
            mFramebuffer = new FrameBufferObject();
            mFramebuffer.bindTexture(mOffscreenTexture);

            mHandler.initWithSize(texWidth, texHeight);
            Common.checkGLError("drawFrame - init handler");
        }

        mHandler.bindTargetFBO();
        GLES20.glViewport(0, 0, texWidth, texHeight);
        drawer.renderTexture(texId, null);
        mHandler.processFilters();
        mFramebuffer.bind();
        mHandler.drawResult();
        return mOffscreenTexture;
    }
}

```
我看到日志里面有两行报错
>07-31 10:43:15.061 25778-25956/com.bhtc.huajuan.push E/libCGE: Load texture mapping0.jpg failed!
>07-31 10:43:15.061 25778-25956/com.bhtc.huajuan.push E/libCGE: Load texture mapping0.jpg failed!

**Comment by forgekxf** [comment]
多谢大师兄，OpenGL不是太了解，我这就改看一下效果！

**Comment by forgekxf** [comment]
已转钱只为表达谢意，请务必收下！🙏

**Comment by wysaid** [comment]
![5zz b _d7 96e057sh6gb](https://user-images.githubusercontent.com/1430725/28761226-ad80b682-75df-11e7-95bf-bcc7415c39f0.jpg)

**Comment by forgekxf** [comment]
大师兄，因为直播我要把渲染好的数据转为byte发送出去，还有多种滤镜一起使用能做到分别调整滤镜强度吗😄

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/include/cgeTextureUtils.h#L189
这里有编码的方法
分别调整滤镜强度这个在demo第一个case里面就有

**Comment by forgekxf** [comment]
嗯，textureId 可以直接转NV21 byte吗

**Comment by wysaid** [comment]
可以的

**Comment by forgekxf** [comment]
int[] frame = new int[1];
        GLES20.glGenFramebuffers(1, frame, 0);
        GLES20.glBindFramebuffer(GLES20.GL_FRAMEBUFFER, frame[0]);
        GLES20.glFramebufferTexture2D(GLES20.GL_FRAMEBUFFER, GLES20.GL_COLOR_ATTACHMENT0, GLES20.GL_TEXTURE_2D, newTexId, 0);

        ByteBuffer buffer = ByteBuffer.allocate(texWidth * texHeight * 4);
        GLES20.glReadPixels(0, 0, texWidth, texHeight, GLES20.GL_RGBA, GLES20.GL_UNSIGNED_BYTE, buffer);
        GLES20.glBindFramebuffer(GLES20.GL_FRAMEBUFFER, 0);
        GLES20.glDeleteFramebuffers(1, frame, 0);

        if (buffer != null) {
            lock.lock();
            buffer.clear();
            bytes2 = new byte[buffer.capacity()];
            buffer.get(bytes2, 0, bytes2.length);
            lock.unlock();
        }
textureId实时转byte，拉流端一直红绿花屏，是格式不对吗？

**Comment by wysaid** [comment]
你这格式没对， 不是说要NV21么， 得自己转

**Comment by forgekxf** [comment]
嗯嗯，需要写shader转吗

**Comment by wysaid** [comment]
对的， 就是前面给你的那个c++的类， 你做个java的版本就行， 具体使用在 cgeVideoUtils.cpp里面有

**Comment by forgekxf** [comment]
c++那块看不太懂，有时间希望封装一下支持各种格式转换的方法～

**Comment by forgekxf** [comment]
外面调用 setFilterWithConfig("@beautify face 1 480 640"); 和 setFilterIntensity(intensity); 没有效果呢

**Comment by forgekxf** [comment]
在加了滤镜的基础上，使用Camera360美颜处理后画面变为纯白色了～TextureRendererDrawOrigin.create(true);应该是这里的原因吧

**Comment by wysaid** [comment]
没有效果那个， 我记得你的demo是有效果的。
纯白的问题你改成false不就知道了。 需要处理的纹理是 external_oes的就给true， 不是就给false， 两者都有就创建俩

**Comment by forgekxf** [comment]
setFilterWithConfig("@beautify face 1 480 640"); 和 setFilterIntensity(intensity); 初始化时有效果，再次手动修改就没有效果了；
关于纯白的问题：
拿到外部纹理，经gpuimage处理后，将处理后的纹理丢给Camera360（纹理设置为接收GL_TEXTURE_2D）再次美颜处理，输出画面就是纯白了，如果直接经gpuimage处理后直接输出图像则正常；
如果不经gpuimage处理直接拿外部纹理交给Camera360处理输出（纹理设置为接收external_oes），图像也是正常的；

**Comment by wysaid** [comment]
把纹理截图成bitmap存盘跟踪一下， 看看是哪一步结果不对吧

**Comment by forgekxf** [comment]
嗯，手动修改滤镜无效会是什么问题呢！一直这么麻烦你真是抱歉～

**Comment by wysaid** [comment]
这个建议你在c++层加一点log看看有没有执行到， 以及穿进去的参数值是多少， 多改几次就熟悉了， 不试试看的话以后遇到了类似的问题还是比较茫然

**Comment by forgekxf** [comment]
嗯

**Comment by forgekxf** [comment]
大师兄你是怎么学习OpenGL和ffmpeg的！

**Comment by wysaid** [comment]
一边学一边做啊， 比如这个repo就是。
它的前身是 github.com/wysaid/wge (只放了一部分比较基础的)
后来项目死了之后用c++重写了一下， 删掉了很多动画模块， 就成了现在这个样子。
你可以用我这个repo当做入门的， 以及还写过一个很烂的教程(webgl)， 就在我的repo list里面

**Comment by forgekxf** [comment]
嗯嗯，多谢🙏

**Comment by wysaid** [comment]
只不过本repo删除了所有动画模块， 没多少难度了。

**Comment by forgekxf** [comment]
大师兄，抱歉还要麻烦你一下，gpuimage和Camera360 SDK合并白屏问题，Camera360说是OpenGL环境问题导致，Camera360 SDK使用的是外部的OpenGL；
我把合并后的代码都提交到fork上了，有时间的话麻烦再看一下！🙏🙏🙏

**Comment by wysaid** [comment]
ok

**Comment by forgekxf** [comment]
大师兄上午麻烦看一下～ 抱歉有点着急...
![image](https://user-images.githubusercontent.com/20853105/28805508-21fe3616-769d-11e7-9851-d01109f09ef8.png)

**Comment by forgekxf** [comment]
大师兄近期有空可以看一下吗……

**Comment by forgekxf** [comment]
合并效果做好后测试打算发到线上，之前太着急不好意思

**Comment by wysaid** [comment]
嗯， 明天看看

**Comment by forgekxf** [comment]
大师兄有时间看下吗？抱歉一直麻烦你！

**Comment by wysaid** [comment]
你给的demo没法测了

**Comment by wysaid** [comment]
建议你自己解决一下跟其他第三方sdk的交互。
我看了下， 问题应该很简单

**Comment by forgekxf** [comment]
好的，多谢大师兄
