### ISSUE TITLE
小米手机调用摄像头聚焦：崩溃

### ISSUE THREAD

**Issue by gzgang** [wysaid/android-gpuimage-plus#181]
Hi 大师兄，我在小米手机上面，调用摄像头聚焦的时候，会出现崩溃，提示说 camera service has die;
这是什么原因呢？

手机型号：红米 3s
系统版本：android 6.0
log信息：
08-03 18:58:22.386 30133-30145 W/CameraBase: Camera service died!
08-03 18:58:22.387 30133-30279 W/CameraBase: mediaserver's remote binder Camera object died
08-03 18:58:22.530 30133-30133 E/Camera: Error 100

08-03 19:00:54.639 30133-30146 W/MediaMetadataRetriever: MediaMetadataRetriever server died!
08-03 19:00:54.639 30133-30146 W/IMediaDeathNotifier: media server died
08-03 19:00:54.639 30133-30146 W/CameraBase: Camera service died!
08-03 19:00:54.641 30133-30146 W/CameraBase: mediaserver's remote binder Camera object died
08-03 19:00:54.644 30133-30145 W/AudioSystem: AudioFlinger server died!
08-03 19:00:54.648 30133-30133 E/Camera: Error 100

**Comment by wysaid** [comment]
能贴一下日志， 以及说一下手机型号么

**Comment by gzgang** [comment]
贴上来日志信息哈，这边几个小米手机都会这样。

**Comment by gzgang** [comment]
找到原因了，是聚焦范围太大了，我打印出来的log：
CameraInstance.java 这个文件里面
focusArea = Rect(1325763, -1000 - 1000, -368486)
看到网上说[ 如果超出了(-1000,1000)到(1000, 1000)的范围，则会导致相机崩溃。](http://blog.csdn.net/afei__/article/details/52033466)

谢谢大师兄回复:)
