### ISSUE TITLE
关于滤镜名字和效果

### ISSUE THREAD

**Issue by YuJunKui1995** [wysaid/android-gpuimage-plus#186]
比如设计要求做日韩滤镜，那这个滤镜相对应要调整什么(这个应该怎么查)，或者Demo中的滤镜对应的叫什么名字

**Comment by wysaid** [comment]
把 https://github.com/wysaid/cge-tools 这个丢给设计， 让他自己调

**Comment by YuJunKui1995** [comment]
已经用demo里的效果和tools搞了一部分滤镜效果了，谢谢大师兄
