### ISSUE TITLE
视频使用滤镜后底部出现绿色条

### ISSUE THREAD

**Issue by YuJunKui1995** [wysaid/android-gpuimage-plus#188]
效果如图
<img src='http://i4.bvimg.com/1949/25ed5172544c6a93.jpg'>
保存代码如下
<img src='http://i4.bvimg.com/1949/95a6d1550aabaadb.png'>
而使用VideoPlayerGLSurfaceView  setFilterWithConfig的正常

不知道哪里错了 大师兄帮忙看下

**Comment by YuJunKui1995** [comment]
用TestCase也一样  只改了inputFileName  也是底边有绿色

**Comment by wysaid** [comment]
不知道耶~
像是视频分辨率对齐问题， 但是我这边没这问题， 你……再检查下？

**Comment by YuJunKui1995** [comment]
这个视频也是demo里的   TestCase的代码也只改了inputFileName 的   您那没问题？我这两台机器  都是有这个问题。。

**Comment by wysaid** [comment]
你换成自己录的视频呢

**Comment by YuJunKui1995** [comment]
我自己录了一个  也是一样出现绿边

**Comment by wysaid** [comment]
你看看输入视频和输出视频分辨率分别是多少呢

**Comment by YuJunKui1995** [comment]
分辨率都是360*480 只是时长在加滤镜后多了一秒

**Comment by YuJunKui1995** [comment]
这个真的无解吗？

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/source/cgeVideoUtils.cpp#L20
把这一行后面的1改成0， 重新编译再试试

**Comment by gzgang** [comment]
@wysaid  大师兄，我这也遇到了这个问题。
把 #define USE_GPU_I420_ENCODING 0 之后没问题了；不过这样之后处理耗时变长了。

**Comment by wysaid** [comment]
估计是GPU编码部分写得有点问题，我这边再检查下

**Comment by YuJunKui1995** [comment]
C:\Users\Administrator>ndk-build NDK_PROJECT_PATH=D:\zxcs\video-processing\library\src\main\jni\ APP_BUILD_SCRIPT=D:\zxcs\video-processing\library\src\main\jni\Android.mk
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-14.
[arm64-v8a] Compile++      : CGE <= cgeGLFunctions.cpp
In file included from D:/zxcs/video-processing/library/src/main/jni/cge/common/cgeGLFunctions.cpp:8:
D:/zxcs/video-processing/library/src/main/jni/include\cgeGLFunctions.h:246:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
make: *** [D:\zxcs\video-processing\library\src\main\jni\/obj/local/arm64-v8a/objs/CGE/D_/zxcs/video-processing/library/src/main/jni/cge/common/cgeGLFunctions.o] Error 1

**Comment by YuJunKui1995** [comment]
ndk编译 找不到#include <vector>

**Comment by wysaid** [comment]
@YuJunKui1995 win下

**Comment by YuJunKui1995** [comment]
已经解决 貌似生成的时间长了
