### ISSUE TITLE
希望提供其他架构的so文件

### ISSUE THREAD

**Issue by forgekxf** [wysaid/android-gpuimage-plus#19]
希望将打包出来的所有so都提供出来, 非常感谢作者

**Comment by wysaid** [comment]
在 no_ffmpeg 分支 有所有架构的so
master分支带neon的ffmpeg， 只需要arm-v7a 就够了。
x86之类的也能跑的

**Comment by forgekxf** [comment]
好的，多谢！我在小米上也遇到了 couldn't find "libx264.142.so" 问题，arm64-v8a架构

**Comment by wysaid** [comment]
repo里面带的demo能跑么

**Comment by forgekxf** [comment]
里面编译好的demoAPK跑起来完全没问题

**Comment by wysaid** [comment]
@forgekxf  那么你就要检查一下你的工程配置了， 混用不同架构的so, 
你可以参考 snow这个app 的包， 里面有很多不同架构的so， 而它的人脸识别、ffmpeg等模块只有arm-v7a目录下有， 别的目录是没有的

**Comment by forgekxf** [comment]
找到原因了，targetSdkVersion 22 就可以正常运行了

**Comment by forgekxf** [comment]
x86 架构无法安装~~~还是希望作者尽量打包出其他的so文件

**Comment by wysaid** [comment]
@forgekxf  同样功能的so在apk里面不同架构放很多份是非常不明智的行为哦。 这种问题你最好解决一下
see this: http://stackoverflow.com/questions/30782848/how-to-use-32-bit-native-libaries-on-64-bit-android-device

**Comment by forgekxf** [comment]
可是，还是希望您能打包出x86架构 和 arm架构的so，这样才能在x86上跑起来的

**Comment by wysaid** [comment]
如果是兼容x86的话， 不需要提供x86版本的， 现在的也可以跑吧
如果是专门定制x86版本的， 倒是应该提供。 后续会补上的

**Comment by forgekxf** [comment]
目前有arm-v7的so，还希望同时提供arm架构的so，多谢啦！

**Comment by forgekxf** [comment]
目前已集成进项目中，希望近期提供arm架构 和 x86 架构so文件，非常感谢！！！

**Comment by wysaid** [comment]
@forgekxf ok.

**Comment by forgekxf** [comment]
麻烦作者尽快提供下arm 和 x86 so文件，早已将您的工程集成进项目中，下周估计要发布版本~~~！多谢！！！

**Comment by forgekxf** [comment]
真心希望作者尽快提供arm so文件，真的非常感谢！

**Comment by wysaid** [comment]
in extra-libs now

**Comment by itheimaAndroid** [comment]
非常感谢作者~~~~！！！

**Comment by forgekxf** [comment]
非常感谢作者~~~~！！！多谢多谢！
