### ISSUE TITLE
Hi wysaid! Can you help me..?

### ISSUE THREAD

**Issue by ssy06005** [wysaid/android-gpuimage-plus#192]
<img width="608" alt="2017-08-17 3 22 13" src="https://user-images.githubusercontent.com/22876537/29398494-02dccd18-8360-11e7-9525-c60d1158d163.png">

I want to change to the custom filter button 
So I wrote a code like a picture above.

But it doesn't work.. ;(
How do I change it?

Somebody help me.

**Comment by ssy06005** [comment]
<img width="509" alt="2017-08-17 3 34 44" src="https://user-images.githubusercontent.com/22876537/29398801-9f7bb30e-8361-11e7-8773-48050356bb61.png">

**Comment by wysaid** [comment]
I don't know what you're doing.
`cgeCreateFilterWithConfig` just create a filter, and return it.
`loadTetureByName` just create a texture with the provided name, and return it.
And you are not using the return value.
Maybe you should learn more~

**Comment by ssy06005** [comment]
Aha.. 
Thanks for commet
I need to learn more java TT
