### ISSUE TITLE
图片滤镜后出现蓝色绿色线

### ISSUE THREAD

**Issue by YuJunKui1995** [wysaid/android-gpuimage-plus#193]
帮忙看下
东部使用了 @curve R(0, 4)(255, 244)G(0, 0)(255, 255)B(0, 84)(255, 194)滤镜
西部使用了  @curve R(15, 0)(92, 133)(255, 234)G(0, 20)(105, 128)(255, 255)B(0, 0)(120, 132)(255, 214)

效果图如下
<img src='http://i4.bvimg.com/606951/f7a233d861d58893.png'>

圆形图的原图为
<img src='http://i4.bvimg.com/606951/83fc69df59b34276.png'>

thanks

**Comment by wysaid** [comment]
哪里有蓝色绿色线

**Comment by YuJunKui1995** [comment]
<img src='http://i4.bvimg.com/606951/0cc72cbd29ccb1de.png'>

**Comment by wysaid** [comment]
把图片分辨率改成2或者4的倍数
然后拿ps打开你这张图的原图， 然后自己把最右边那一列像素擦干净
你这张图尺寸是奇数， 大概在bitmap里面会有奇怪的对齐

**Comment by YuJunKui1995** [comment]
改成这样还是有问题
<img src='http://i4.bvimg.com/606951/506915b4321eb29d.png'>

**Comment by wysaid** [comment]
改成256或者128试试

**Comment by YuJunKui1995** [comment]
改了256还是不行  我让设计给了两个滤镜后的图  直接用资源了

**Comment by YuJunKui1995** [comment]
谢谢啦
