### ISSUE TITLE
关于暂停的问题

### ISSUE THREAD

**Issue by stayinxing** [wysaid/android-gpuimage-plus#199]

**Comment by wysaid** [comment]
当然可以， 自己实现一下这些功能吧

**Comment by stayinxing** [comment]
我在demo的pause按钮的stopPreview()方法里，调用了   mFrameRecorder.pauseRecording(); 结果就是：    Pause function is not completed by now!! 求指教！！！

**Comment by wysaid** [comment]
所以说自己实现一下啦~

**Comment by stayinxing** [comment]
主要C++，不会啊。void CGEFrameRecorder::pauseRecording()
	{
		//Not provided by now.
		// m_isRecordingPaused = true;
		CGE_LOG_ERROR("Pause function is not completed by now!!");
	}

最后这个方法是这样的，我在想要不然，每次走ending,然后把多段短视频拼接成一个长视频，不知道可不可行。

**Comment by wysaid** [comment]
多段拼最好
