### ISSUE TITLE
可以提交到jcenter吗？

### ISSUE THREAD

**Issue by pengjianbo** [wysaid/android-gpuimage-plus#2]

**Comment by wysaid** [comment]
咦， 还能这样， 得空了我试试看

**Comment by pengjianbo** [comment]
gradle引用。不可能下载你的源码来运行吧。嘻嘻

**Comment by wysaid** [comment]
好的， 感谢提醒

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/commit/74dbae58669a3e2e48fdad5e8d04a7d917e1f833
