### ISSUE TITLE
免费的人脸识别

### ISSUE THREAD

**Issue by YuJunKui1995** [wysaid/android-gpuimage-plus#200]
http://www.arcsoft.com.cn/  用着还可以

**Comment by wysaid** [comment]
几年前了解到一年收费五十万以上， 且绑定app id, 跟sensetime, face++的策略差不多的。
刚才注册了一个账号试了一下， 也是需要在线验证， 你们自己弄一下吧

**Comment by YuJunKui1995** [comment]
这个现在是免费，可以用来做 人脸贴图啊

**Comment by wysaid** [comment]
soga, 我可以新开一个repo, 做一个简单demo

**Comment by YuJunKui1995** [comment]
期待。

**Comment by wysaid** [comment]
···
typedef struct {
    MInt32 nFace;                        // number of faces detected
    AFT_FSDK_OrientCode lfaceOrient;     // the face angle
    MRECT *rcFace;                       // The bounding box of face
} AFT_FSDK_FACERES, *LPAFT_FSDK_FACERES;
···
这是免费sdk的人脸检测结果， 并没有landmark， 所以没有任何意义
检测矩形区域的话太简单了

**Comment by YuJunKui1995** [comment]
是的  他只有脸框和人脸角度。做人脸贴图也只是做 简单效果

**Comment by wysaid** [comment]
不如内嵌的FaceTracker好使

**Comment by YuJunKui1995** [comment]
FaceTracker不是要转bitmap  这样运算不是又回到cpu？

**Comment by wysaid** [comment]
FaceTracker只需要图像数据， 其他的都是我写的， 包括bitmap转换， 你自己改一下就行

**Comment by YuJunKui1995** [comment]
多谢

**Comment by YuJunKui1995** [comment]
公司要求使用哪个虹软的人脸识别做 贴图， 大师兄是提供下 基于项目做的步骤吗

**Comment by wysaid** [comment]
你们公司用的付费的带landmark101的sdk还是就是这个免费的？

**Comment by YuJunKui1995** [comment]
免费 的

**Comment by wysaid** [comment]
两个方法，
 - 劝一下你们老板
 - 离职

用内建的facetracker都比那玩意强

**Comment by YuJunKui1995** [comment]
但是facetracker 的识别速度用于视频人脸识别  速度有点慢吧应该

**Comment by wysaid** [comment]
异步处理

**Comment by YuJunKui1995** [comment]
这样如果人脸位置或者其他变化    贴图还是延迟贴上去的应该

**Comment by YuJunKui1995** [comment]
如果按照四个点硬贴，是不是跟每帧不同的水印 原理一样？

**Comment by wysaid** [comment]
放弃吧

**Comment by YuJunKui1995** [comment]
呃  那我试下劝劝他们

**Comment by wysaid** [comment]
landmark101 的版本可以做， 年费单平台30~50w， 劝他们买一个吧。
据我了解， arcsoft最便宜， face++ 其次, sensetime最贵， 你们自己选吧
