### ISSUE TITLE
FFmpeg issue - resulting video's audio is slowed down, resulting in a longer video

### ISSUE THREAD

**Issue by NiekAkerboom** [wysaid/android-gpuimage-plus#206]
Hello,

I'm having the following issue when generating the resulting video using FFmpeg. The resulting video's audio seems to be slowed down by a decent amount, this means that the video ends up being longer than the source video. The final frame of the video will be shown for the extra x seconds (depending on the source length) or you'll see a black screen and just hear the audio continue.

I made [a video](https://youtu.be/AU2kR6aRn3s) where you can see that the source video is 2:50 in length and the filtered one ends up being 3:05 in length which means that the audio is slowed down by almost 9%. I'm not counting out that the image part isn't flawless, but most noticeable by far is the audio being slowed down.

I'm able to reproduce this issue on every device that I've tried so far (oneplus one, oneplus five, google pixel) using the latest code. I'm unable to find any submitted ticket about this which I find a bit weird.

Is your FFmpeg-ed video the same length as your source video? Do you know what the issue could be?

Thank you for your time.

**Comment by wysaid** [comment]
Get it, I will test on my device

**Comment by NiekAkerboom** [comment]
Thanks, appreciate your hard work.

**Comment by NiekAkerboom** [comment]
Did you find the time to check it out yet?

**Comment by wysaid** [comment]
@NiekAkerboom I tried on the newest code, no such problem.
Are you using the builtin demo? It may be too old.

**Comment by NiekAkerboom** [comment]
I'm using the following provided method:

`CGEFFmpegNativeLibrary.generateVideoWithFilter(arguments);`

I've tried it after pulling the latest code from this repo and also when I implement it in my own project. Is there a different method that I should be using?

**Comment by wysaid** [comment]
@NiekAkerboom  Have you tried the latest code with the simple demo?
Maybe the output video's `FPS` should match the input one, but my demo did not do that.

**Comment by NiekAkerboom** [comment]
Thanks for the quick comment, I'll check this out today and will report back once I double checked if the source FPS is the same.

**Comment by NiekAkerboom** [comment]
@wysaid I've been testing it with the latest code today, still having the issue. Tested it on 4 devices so far. I'm building the library using android-ndk-r13b and tried IDE AS3.0 and AS2.3.3 The video that I'm using is one that I recorded myself and [this sample video](http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_10mb.mp4).

Using the sample video the generated video is 1:08 in time while the source is 1:02 in time. I haven't altered any of the code. Nothing changes if I [change the FPS here to 25](https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/source/cgeVideoUtils.cpp#L117) to match the frame rate of the sample video, still results in 1:08 in length.

The method that I'm running in the demo app is **testCaseOffscreenVideoRendering** which is found in the **TestCaseActivity**.

Thanks again for checking it out!

**Comment by wysaid** [comment]
OK, get it. I will check it again with your sample video.

**Comment by NiekAkerboom** [comment]
Thanks! If you're still unable to reproduce it, could you update the demo APK? It's a long shot, but if I can still reproduce it using your APK I can count out my building process as being the source of the issue.

**Comment by wysaid** [comment]
@NiekAkerboom I can see the problem now.
The video will be longer than the origin, and there are blank frames in the end.

**Comment by NiekAkerboom** [comment]
Yes! That's exactly what's happening. When you play the original and edited video at the same time you can see that the video stream is applied correctly. The audio, however, keeps playing. In the sample video you can hear that the bear's yawn at the start has a lower pitch, so my guess is that for some reason the audio is applied slowed down by a small percentage.

**Comment by wysaid** [comment]
Solved!  It's my mistake, I forgot to assign the audio's sample rate to the `addStream` function.
See this commit: https://github.com/wysaid/android-gpuimage-plus/commit/889b9e454a88bfb841b5aa072589b8f772bb2615

**Comment by wysaid** [comment]
It happened when the input audio sample rate is not 44100.

**Comment by NiekAkerboom** [comment]
Awesome, Really appreciating your work! Tested and it indeed seems to be solved.
