### ISSUE TITLE
请问一下本地视频加滤镜后怎么保存呢？

### ISSUE THREAD

**Issue by LukaHan** [wysaid/android-gpuimage-plus#21]

**Comment by wysaid** [comment]
后续会支持， 到时候demo里面会有所体现

**Comment by dasamanren** [comment]
同求~~希望能早点实现,谢谢大神

**Comment by wysaid** [comment]
已支持

**Comment by wanlijiangshan** [comment]
没有找到保存按钮啊  求指导啊  那个按钮可以保存成本地视频

**Comment by wysaid** [comment]
Test case里面有

**Comment by wanlijiangshan** [comment]
感谢 再问一个问题  就是保存成本地视频这里面只能添加一种滤镜吗  可以选择其他滤镜添加吗

**Comment by wysaid** [comment]
任何滤镜都可以， 也可以自己写

**Comment by wanlijiangshan** [comment]
您好  我使用Test case里面的保存成另一个视频  发现如果我导入的是手机中自己的视频  发现新保存的视频带一条绿边  并且视频角度旋转了90度  这个可以调吗
