### ISSUE TITLE
App crash after add com.facebook.fresco:fresco:1.5.0

### ISSUE THREAD

**Issue by WyJong** [wysaid/android-gpuimage-plus#213]
Hi Wysaid, I added com.facebook.fresco:fresco:1.5.0 in your sample then app crash and I got "Could not find ffmpeg.so" 

https://github.com/facebook/fresco

![screen shot 2017-09-09 at 7 57 59 am](https://user-images.githubusercontent.com/30853945/30235789-415c5ea8-9537-11e7-9922-2289c4a36159.png)

**Comment by wysaid** [comment]
Maybe `fresco` uses other archs, you can just add all archs of the JNI module  in your code.

**Comment by WyJong** [comment]
Thank you. It's working.
