### ISSUE TITLE
三星S8播放MP4偶尔能放出，大部分情况下黑屏

### ISSUE THREAD

**Issue by sxlvalue** [wysaid/android-gpuimage-plus#215]
参考了示例：VideoPlayerDemoActivity写的代码，因为要根据数据是图片还是视频所以ImageGLSurfaceView和VideoPlayerGLSurfaceView放在同一个界面，不知道是不是这个问题引起的。

mVideoView.setVisibility(View.VISIBLE);
        mImageView.setVisibility(View.GONE);
        mVideoView.setZOrderOnTop(true);
        mVideoView.setZOrderMediaOverlay(true);
            mVideoView.setOnCreateCallback(new VideoPlayerGLSurfaceView.OnCreateCallback() {
                @Override
                public void createOK() {
                    showBlurVideo(mFilePath);
                }
            });

public void showBlurVideo(final String filePath){
        final Uri videoUri = Uri.parse(filePath);

        if (null != mVideoView){
            String config = isBlur ? EFFECT_CONFIGS[1] : EFFECT_CONFIGS[0];
            mVideoView.setFilterWithConfig(config);
            mVideoView.setPlayerInitializeCallback(playerInitializeCallback);
            mVideoView.setVideoUri(videoUri, new VideoPlayerGLSurfaceView.PlayPreparedCallback() {
                @Override
                public void playPrepared(MediaPlayer player) {
                    Log.i(Common.LOG_TAG, "The video is prepared to play");
                    //player.start();
                    mVideoView.post(new Runnable() {
                        @Override
                        public void run() {
                            MsgUtil.toastMsg(mContext, "Start playing " + videoUri.getHost() + videoUri.getPath());
                        }
                    });
                    player.start();
                }
            }, playCompletionCallback);
           

        }
    }

**Comment by wysaid** [comment]
同一个activity里面不要同时存在两个glsurfaceview

**Comment by sxlvalue** [comment]
我同时存在ImageGLSurfaceView和VideoPlayerGLSurfaceView，因为我要根据数据源是图片或者视频显示不一样的内容，不过我把视频源换成本地录制的视频就可以了

**Comment by wysaid** [comment]
那大概是安卓自带的MediaPlayer的问题了@_@ 
你可以自己实现一个， 支持两者， 或者就把这两个合成一个， 用一个参数判断一下

**Comment by sxlvalue** [comment]
谢谢wysaid，关注了很久的项目，原来如此强大，感谢wysaid的付出。
