### ISSUE TITLE
Can you please help?

### ISSUE THREAD

**Issue by shubhwicked** [wysaid/android-gpuimage-plus#224]
I am saving video with filter after selecting a video from gallery, but it is rotated by mostly 90 degrees, and a green line has been added to the video, can you please help in that?

**Comment by CheyenneForbes** [comment]
try recording a video with another app and tell me if you get the same line

**Comment by wysaid** [comment]
Please checkout the latest code.

**Comment by shubhwicked** [comment]
ok i am checking it.

**Comment by shubhwicked** [comment]
Now it is perfect, thank you very much buddy, keep coding :)

**Comment by NiekAkerboom** [comment]
Hey @wysaid, what has been changed in the code? Only the .SO file has been adjusted.

**Comment by wysaid** [comment]
Just changed this line, and recompiled the library: https://github.com/wysaid/android-gpuimage-plus/commit/16cd891675e2ffdd32f51781e193d9201827944e

**Comment by NiekAkerboom** [comment]
Ah right, thanks!
