### ISSUE TITLE
android-gpuimage GPUImageNativeLibrary.YUVtoRBGA

### ISSUE THREAD

**Issue by Heuid384** [wysaid/android-gpuimage-plus#231]
你好,我使用android-gpuimage 这个库的时候,相机预览画面在低端设备上比较卡,主要是在onPreviewFrame方法里面调用了GPUImageNativeLibrary.YUVtoRBGA回调显示,cpu每秒要处理大约30帧720x1280的数据,我尝试过将这个方法换掉,但是都失败了!我用你这个库的时候感觉预览界面非常流畅,请问你是怎么实现的呢?

**Comment by Liu939** [comment]
I find the problems ,thanks
