### ISSUE TITLE
问个倒播技术问题

### ISSUE THREAD

**Issue by jiriyao** [wysaid/android-gpuimage-plus#235]
视频倒播给个思路大师兄，
我的思路是从视频最后一帧开始读取bufferimage，然后倒序写入成视频。多谢：）。就是倒序读取视频的关键帧图片再组织为视频，可行么？

**Comment by wysaid** [comment]
当然可以啊。。。

**Comment by jiriyao** [comment]
我看到jcodec这样的库提供按时间seek的方法，有没有 直接获取某个关键帧的方法呢？而不是seek

**Comment by wysaid** [comment]
没用过， 不知道

**Comment by jiriyao** [comment]
哦，好的，谢谢。
