### ISSUE TITLE
CGEDataParsingEngine::adjustParser Create Lookup filter Failed

### ISSUE THREAD

**Issue by WindSekirun** [wysaid/android-gpuimage-plus#239]
Hello.
I have error when apply ````@adjust lut lookup_pink.png```` in application.
To re-produce this problem, i made simple sample project.

#### Environment
Android Studio 3.0 Beta 7 in Windows 10 / 2.2.3 in Windows 10
Include Kotlin Plugin, but main code written by Java.

using 'org.wysaid:gpuimage-plus:2.4.9' (i tried 2.4.6-min, too)

#### Code & Structure
[[Repo]](https://github.com/WindSekirun/GPUImagePlusTest) [[Activity Code]](https://github.com/WindSekirun/GPUImagePlusTest/blob/master/app/src/main/java/pyxis/uzuki/live/gpuimageplustest/MainActivity.java) [[XML Code]](https://github.com/WindSekirun/GPUImagePlusTest/blob/master/app/src/main/res/layout/activity_main.xml)

![package structure](https://user-images.githubusercontent.com/3054645/31920839-65748760-b8a6-11e7-893e-5f3350ba50c3.PNG)

#### Step
1. run this sample
2. click 'FILTER' button

#### Logcat
````
E/libCGE: Load texture lookup_pink.png failed!
E/libCGE: CGEDataParsingEngine::adjustParser Create Lookup filter Failed
E/libCGE: 特效指令 "@adjust lut lookup_pink.png" 无法生成任何特效!
````

Am i missing somewhere? 
When i tried run cgeDemo, it was work in same environment.

**Comment by wysaid** [comment]
Have you called the [CGENativeLibrary.setLoadImageCallback](https://github.com/wysaid/android-gpuimage-plus/blob/master/cgeDemo/src/main/java/org/wysaid/cgeDemo/MainActivity.java#L240)?

**Comment by WindSekirun** [comment]
Oh.....
Yes, it's work. Thanks a lots, and Thanks for fast response.
