### ISSUE TITLE
编码时可以添加水印吗？

### ISSUE THREAD

**Issue by forgekxf** [wysaid/android-gpuimage-plus#24]
大师兄，编码时可以添加水印吗？

**Comment by wysaid** [comment]
你自己丢一个图片滤镜进去就可以啦， 比如 @blend mix xx.png 100

**Comment by forgekxf** [comment]
嗯嗯，比如图片位置，还有就是我想做到编码的时候再自动生成水印，不是在录制的时候~~~

**Comment by tingfengainiaini** [comment]
我也想做这个功能。就是视频贴图、添加文字、添加画笔的功能。想在编码过程中做。
基本也是类似另外一个issue中说的，想做一个类似faceu、snow的东西。目前图片贴图、文字做好了。face detection、tracking、aliengment的东西也正在研究。视频这部分gl相关的着实不太会。
jni源码能否公布，造福一下才初学者？万分感谢啊

**Comment by wysaid** [comment]
后期会提供~

**Comment by tingfengainiaini** [comment]
万分感谢，期待！

**Comment by wysaid** [comment]
已添加， 请更新 @tingfengainiaini  @forgekxf

**Comment by tingfengainiaini** [comment]
研究一下！感谢！
