### ISSUE TITLE
大师兄，离屏渲染视频，如果视频15秒，就得渲染15s怎么样才能不依赖时间

### ISSUE THREAD

**Issue by chongbo2013** [wysaid/android-gpuimage-plus#241]
大师兄，离屏渲染视频，如果视频15秒，就得渲染15s怎么样才能不依赖时间

**Comment by wysaid** [comment]
本来就没有依赖时间啊， 渲染得久只是因为这一块代码很粗糙， 运行很慢~ 你需要自己优化一下

**Comment by chongbo2013** [comment]
原来哈，大师兄有稍微提下优化思路吗，还有 视频画面区域裁剪

**Comment by wysaid** [comment]
cgeVideoUtils.cpp 那个文件上面有个开启 GPU加速的宏， 写成1能加快一些
但是分辨率需要是8的整数倍， 否则可能出现一些绿边问题， 其他issue里面出现过， 所以默认把这个功能关了的， 如果你觉得你的视频分辨率是满足8的倍数的， 就可以直接开启。

**Comment by chongbo2013** [comment]
明白，大师兄画面裁剪区域呢

**Comment by wysaid** [comment]
自己设一下fbo大小和viewport就搞定的， 自己加一下吧

**Comment by chongbo2013** [comment]
ok 这个 能搞定， 媒体输出的是不是要需要设置下分辨率， 大师兄 谢谢哈，一会捐献红包

**Comment by chongbo2013** [comment]
我看你 好像处理了，如果不是8的倍数，分辨率输出就设置8的倍数
//The video height must be mutiple of 8 when using the gpu encoding.
        if(videoHeight % 8 != 0)
        {
            videoHeight = (videoHeight & ~0x7u) + 8;
        }

**Comment by wysaid** [comment]
嗯， 你先试试吧

**Comment by chongbo2013** [comment]
好
