### ISSUE TITLE
GPUImage SmoothToon Filter

### ISSUE THREAD

**Issue by AuxanoWeb** [wysaid/android-gpuimage-plus#250]
Hi, I want to implement custom filter effect like "SmoothToonFilter(Intense) Effect."
Please help me by providing any "adjust" string for SoothToon Filter.
I tried to many HSL Values for this but not succeed.
for e.g. "@adjust hsl 0.5 0.2 10.0"

**Comment by wysaid** [comment]
Why don't you just write this filter in the jni module?

**Comment by wysaid** [comment]
- Wiki for rule string: https://github.com/wysaid/android-gpuimage-plus/wiki/Parsing-String-Rule-En
- tool for rule string: https://github.com/wysaid/cge-tools
They're all in the main page https://github.com/wysaid/android-gpuimage-plus.

**Comment by wysaid** [comment]
The effect you sent me may need cross steps, and the rule string may not fit that.
For the original image(set as `A`), do `@style edge 1 2 @adjust saturation 0 @curve RGB(0, 255)(255, 0) ` and get the result as __B__  
Then do a multiply like `@blend multiply B 100 `, the effect is done.

**Comment by AuxanoWeb** [comment]
Excellent job, Yes its work, but there is minor difference found like in effect the COLOR part is changed with WHITE part, in effect, there are only two colors found black and white.  I want to keep color in effect. so please help me which particular value change give the desired result. Thanks a lot for your kind help.

**Comment by wysaid** [comment]
Maybe you can change  `@style edge 1 2 @adjust saturation 0 @curve RGB(0, 255)(255, 0)` to `@style edge 1 1.5 @adjust saturation 0 @adjust level 0.34 0.67 1 `

You can repeat the steps on the [filter tool](https://github.com/wysaid/cge-tools), and try to get a better look.

And the easiest way is just write a special filter for that. It will run faster.

**Comment by AuxanoWeb** [comment]
Excellent job, Yes its work, but there is minor difference found like in
effect, the COLOR part is changed with WHITE part. In effect, there are
only two colors found black and white. I want to keep color in effect. so
please help me which particular value change give the desired result.
Thanks a lot for your kind help. I used your string like,

"@blend <https://github.com/blend> multiply @Style
<https://github.com/style> edge 1 2 @adjust
<https://github.com/adjust> saturation
0 @curve <https://github.com/curve> RGB(0, 255)(255, 0) 100".


You can see the first image has just black and white color while the second
image has real color.
I want to set effect same as the second image has with real color.

**Comment by AuxanoWeb** [comment]
Brother this String
@style edge 1 1.5 @adjust saturation 0 @adjust level 0.34 0.67 1

gives a result like the attached image.

**Comment by wysaid** [comment]
I changed this, please check again.

**Comment by AuxanoWeb** [comment]
This string gives the same result as i shared image as before

@style edge 1 1.5 @adjust saturation 0 @curve RGB(0, 255)(255, 0) @adjust
level 0.34 0.67 1

**Comment by wysaid** [comment]
I can't see what you shared.

**Comment by AuxanoWeb** [comment]
I just shared the image in mail with using the string 
@style edge 1 1.5 @adjust saturation 0 @curve RGB(0, 255)(255, 0) @adjust level 0.34 0.67 1

**Comment by AuxanoWeb** [comment]
Brother, there is also one way to achieve that effect fill same as i want. I have .cpp and .h file for that effect but i don't know how to configure that files in jni and how to call so can you please help me how to use .cpp and .h file by doing code.

**Comment by AuxanoWeb** [comment]
Brother, I got the desired result by setting this string
@style edge 1 2 @adjust saturation 0 @curve RGB(0, 190)(190, 0) @adjust level 0.67 0.67 1
and seek progress 0.25.
Thanks a lot, brother, without your help, It would be not possible. Ones again thanks a lot.

**Comment by wysaid** [comment]
😋

**Comment by AuxanoWeb** [comment]
Hi Friend,
Please help me. I need your help.
I want to merge two filters and set to camera preview? like I want to apply
black and white filter with smoothing filter.
I used filter for black and white : "@adjust hsv -1 -1 -1 -1 -1 -1"
I used filter for smoothing : "@beautify face 1.5 480 640".

Please help me brother. Your help save my carrier.

**Comment by wysaid** [comment]
pass `@adjust hsv -1 -1 -1 -1 -1 -1 @beautify face 1.5 480 640`

**Comment by AuxanoWeb** [comment]
Yes brother, thanks a lot, will check and let you update. sorry for late
reply. actually i was on leave so could not reply to you.
