### ISSUE TITLE
Original camera resolution on takePicture

### ISSUE THREAD

**Issue by latsson** [wysaid/android-gpuimage-plus#251]
Hi!
Really nice library.

I have one question/request. I want to save images in the original resolution of the camera.
I can see in the takePicture method in CameraGLSurfaceView, that there is some resizing of the image.

If I take a picture, right now it will be 720x960. A regular camera image for me is 4032x3024.
Thanks.

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/blob/master/cgeDemo/src/main/java/org/wysaid/cgeDemo/CameraDemoActivity.java#L266
Change this line

**Comment by latsson** [comment]
Thanks!
