### ISSUE TITLE
Negative filter

### ISSUE THREAD

**Issue by latsson** [wysaid/android-gpuimage-plus#252]
Hi. Thanks for the awesome work.

I am trying to understand how to do a negative filter. Like the example here: http://webvision.med.utah.edu/wp-content/uploads/2012/06/laura_galloway_invert.jpg

All colors should just be inverted, so 1-r, 1-g, 1-b. I'm trying to understand your "Parsing string rule".
adjust format: "@adjust <function> <arg1>...<argN>"

I'm not sure if I can use a variable to get the rgb values and subtract from 1, or do I need to write a custom shader for that. Could someone please help me how to get this to work.

Another thing, maybe you should change the All arch: armeabi, armeabi-v7a, arm64-v8a, mips, x86 to the recommended, since most android phones have arm64-v8a now.

**Comment by wysaid** [comment]
`@curve RGB(0, 255)(255, 0) `

**Comment by wysaid** [comment]
>Another thing, maybe you should change the All arch: armeabi, armeabi-v7a, arm64-v8a, mips, x86 to the recommended, since most android phones have arm64-v8a now.

Go find any popular apps such as snapchat,  download its apk, decompress it, and you'll know why.

**Comment by latsson** [comment]
Thank you!

Okay, I was just having trouble getting the library to work on my Galaxy S8+ with this gradle dependency. compile 'org.wysaid:gpuimage-plus:2.4.6-min-armv7a', it could not find libCGE.so since it was only located in armeabi-v7a, but the S8+ has a arm64-v8a, but I guess you know more about this than me 😄

**Comment by wysaid** [comment]
You can try the builtin demo with your device.
