### ISSUE TITLE
Can we add animated sticker to video?

### ISSUE THREAD

**Issue by vxhviet** [wysaid/android-gpuimage-plus#261]
Hi @wysaid ,

I've been using your awesome lib for quite a while now but mostly for image manipulation (without ffmpeg and open cv stuff). Now my project requires to take it to a new level, manipulate video. There's two key features that I would like to implement:
- Trim and cut a portion from a video clip (ideally should be able to cut at B-frames, not just key frames).
- Overlay an animated sticker over it (this part I'm not so sure how to implement it).

What I'm looking for is very similar to this:

[Youtube](https://youtu.be/v5h2tI_Bia0?t=2m33s)

This can be easily done with the [AVVideoComposition](https://developer.apple.com/documentation/avfoundation/avvideocomposition) API on iOS. Sadly, such power is not currently available on Android.

**Comment by wysaid** [comment]
You can write some code with ffmpeg to trim and cut the video.   
Maybe ffmpeg command line will make this easier.

And the sticker can be done by a customized filter. Please try to write a new filter about that.

**Comment by vxhviet** [comment]
Hi @wysaid ,
Thank you for your fast response, when you say to write a new filter for the sticker overlay, do you mean something like the [`cge/filters/`](https://github.com/wysaid/android-gpuimage-plus/tree/master/library/src/main/jni/cge/filters) or something I can generate with [`cge-tools`](https://github.com/wysaid/cge-tools)?

**Comment by wysaid** [comment]
The first one.  
You may have to write some c++ code and rebuild the JNI module.

**Comment by vxhviet** [comment]
Thanks a lot, I'm not familiar with C++ but I will give it a try.

**Comment by wysaid** [comment]
👍

**Comment by vxhviet** [comment]
Sorry to bother you @wysaid,

I would like to ask again to make sure I understand the problem correctly. I've been playing around with your CGEdemo and I've seen quite a bit of filters that are used for both image and video (the filters in [`cge/filters`](https://github.com/wysaid/android-gpuimage-plus/tree/master/library/src/main/jni/cge/filters)). If I understand correctly, those filters are based on OpenGL and not really connected to `ffmpeg`? So the flow looks like this:

Use a `Surface` to decode the video -> Apply OpenGL filter to that `Surface` for desired effect -> Use `ffmpeg` to create a video with effect.

Is it the correct flow?

**Comment by wysaid** [comment]
Yes, the ffmpeg just did the video encoding.
You can checkout the branch `min`, and see the result without ffmpeg.
