### ISSUE TITLE
图片局部颜色调整

### ISSUE THREAD

**Issue by yungs2017** [wysaid/android-gpuimage-plus#268]
想请教关于一张图片指定调整局部的颜色（如HSV）应该使用框架的哪个功能呢？

**Comment by wysaid** [comment]
[这里有hsv以及hsl和可选颜色之类的](https://github.com/wysaid/android-gpuimage-plus/wiki/Parsing-String-Rule-En#adjust-format-adjust-function-arg1argn)

**Comment by yungs2017** [comment]
@wysaid 感谢
不过我其实是想要调整一张图片里面某一部分的颜色（如一张房屋照片只调节屋顶的颜色其他的不改变），请问有没有相关的方法呢？

**Comment by wysaid** [comment]
你搜一下 `photoshop 可选颜色`
支持这个功能，
如果你说的是划分图片区域， 比如屏幕某个区域的变色， 那么就自己写个滤镜实现你想要的

**Comment by yungs2017** [comment]
@wysaid 好的，感谢
