### ISSUE TITLE
大师兄，求提供x86架构so文件~~~

### ISSUE THREAD

**Issue by forgekxf** [wysaid/android-gpuimage-plus#27]
目前生产环境线上x86架构手机出现崩溃现象，麻烦再次提供下x86架构so文件~~~！

**Comment by wysaid** [comment]
@forgekxf 
x86的没有neon等东西， 编译出来的ffmpeg 比较慢， 我还没找到原因， 我这周再试试吧。
你确定是这个的关系？ 能否贴几个崩溃日志？

**Comment by wysaid** [comment]
@forgekxf 
以及， 对于视频编解码有更高要求的话， 建议参考 https://github.com/google/grafika
使用硬编码实现性能更佳。 我会不定期同步no_ffmpeg 分支下的代码

**Comment by forgekxf** [comment]
恩恩，我想做到兼容就可以，因为我的项目不是专门做视频的，下面是错误的信息，比较长，重点在最后几行~~~

**Comment by forgekxf** [comment]
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-java-0.5.1_7866197f6370f14b75ff4901bbb2e2f82a1462e0-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-exo-0.5.1_a801e3f2c6de610238fd8865c8db796856a767a1-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-armv7a-0.5.1_20ecdf88dae35860baa7f958595099471f31302c-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-support-annotations-23.1.1_b3b4af8dbd9fcf8f1b1a74a807d3f5c4f4c6a70c-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-qiniu-android-sdk-7.0.10_fdc2a38effae4df79d5047957d2b0008520b772c-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-pinyin4j-2.5.0_62810e4d94b5f6b5a4f0e5b21c22abafffea6fa7-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-org.apache.http.legacy_59674b91c8ba892d7d1436fd4218d508bfe91547-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-okio-1.6.0_a4ab678c71bf682d0e91416e7228da917fc9c6dd-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-okhttputils-2_3_8_1ba3ba08d3577005333d7f4fa95c327853bf2e43-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-okhttp-3.0.1_57745d28f9b5488e4d1c02e3feff3a766f0947ec-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-logging-interceptor-3.0.1_5aba017488d7471b30acbdc317b402e3098e54cd-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-libpingpp-2.1.0_09151760c20cb4bd0c454d22f1f77df40ff1612e-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-libone-2.1.0_896b7a02483d57896f2cb983b342c674b267da39-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-libammsdk_0dba94837cf696e93802307f66f966a6a8463ebb-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-isoviewer-1.0-RC-28_5296944d31b350a511dc6b094f16033820fc69e7-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-internal_impl-23.1.1_001281773e757d321f89e96130fae4fb06807cd1-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-instant-run_70fee5279d1fb54e7b2ff96973b156d2ab27e8b4-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-instant-run-bootstrap_5efc3fb8c02be93d8a4765af5cbdf8d09b10fca6-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-httpclient-4.3.6_2dff9c5181ce43253cf85c1e1ee85b582d53ec0a-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-happy-dns-0.2.5_1c7ada353d746066ad8d2cb4c5a817c1a283375d-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-gson-2.6.2_c0deae0a572880c77f963606f9954c8c4a8551a9-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-glide-3.7.0_f5813f8dbaca8556b51df07c146a7d23ab8e2cbf-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-eventbus-3.0.0_1856975ce1e5f083a9ad4195c5089c5b6fe466f4-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-easemobchat_2.2.9_b9b47a02aadc749346a8147953e664a50e1e4b02-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-core_3.2.0_e8f3d63ae9d5fffe411b444e3181b48f1e10568b-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.tencent.bugly-crashreport-1.2.9_7fb6595a6f5738f7348a174e1f74972e95454ee5-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.google.android.exoplayer-exoplayer-r1.5.7_2dd50cdbec22c552454833079663acdfb02fd7d5-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.github.siyamed-android-shape-imageview-0.9.3_6b3cb8583aa76aaa2dc5b9ef688d94b60cac64af-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.github.rey5137-material-1.1.1_bc9c7918d194d4b165918b33415c27604d9fb5a2-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.dodola-rocoo-1.1_498dd44b6f1688ff92f3d54831ee9eff541c04d8-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.commit451-PhotoView-1.2.4_7517649b7a4a7d37dddd799a37360b26c0da4d09-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.bugtags.library-bugtags-lib-1.2.6_07541ce72d105fe8bb711659f40fea72392456ff-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.android.support-support-v4-23.1.1_b3c6e7122566fb6b5a956318688cb483886e777a-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.android.support-recyclerview-v7-23.1.1_07db5c7e78ed103e4b391d82b37ab2dca5ceaa08-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.android.support-multidex-1.0.1_0116eacd0893e35e6fb57f93ff6aa56f89b8fedb-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.android.support-design-23.1.1_a05cfe038a66ae9a1e9a0697be3927aaa564588d-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.android.support-cardview-v7-21.0.2_675fe1988d00ba7de17c45f7fce6ae1d61c4818c-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.1.1_2c2952bd3c80b001187640350e705ec904854948-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-android-async-http-1.4.9_9d6f7cbc8f8826aad67bda30450043515b21f9bc-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-analytics-6.0.1_49362c1f8774bd0cd585d1824526634d18cf71a1-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-alipaySingle-20160111_43b9a78bd5a747415e0cff244cac22e6c9211e36-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-UPPayPluginExPro_b2c08cacfd2db7614ac335619befa783baea40e7-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-UPPayAssistEx_d11ef6d097d1fe1e2d8ff1fa47d44bc9346e1ad3-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-TalkingdataAnalytics_12180840404695a513b089a3a709b8d7f3037818-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-ShareSDK-Wechat-Moments-2.7.2_9f3a8022c4436ed799f24bd567a342463249aee9-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-ShareSDK-Wechat-Core-2.7.2_e80893826738aec26ad1ba6553008ece9197c0f4-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-ShareSDK-Wechat-2.7.2_f6271c43d8df2aa525819596f95ea3d4a333192f-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-ShareSDK-SinaWeibo-2.7.2_ca1ce4da5223a1be8c91dc372cdb5a1d757d9655-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-ShareSDK-QQ-2.7.2_ddc4fe7a8cf9be83303038a8beb759850cfb1cc1-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-ShareSDK-Core-2.7.2_5bf2b1147f0785b4b0ab978e213636ee301760cf-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-MobTools-2016.0426.1819_25ec71a8b87de270dba699c7fc8c910feb2b6a7c-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-MobCommons-2016.0426.1819_e2c0c60418546d90954658db4b7d56d5c4f6ee2d-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-MiPush_SDK_Client_2_2_21_d98f72245abffb624b0c723114cc722ca2ca0896-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-GetuiSDK2.8.1.0_af9f1471150cd0df0129ce8ffae28bb08256cf16-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-GetuiExt-2.0.3_cf2418b7ff87edb7d035fdc4199aa6d4fc12ff15-classes.dex", dex file "/data/data/com.bhtc.huajuan/files/instant-run/dex/slice-Cashier_SDK-v4.2.2_70150e907cbc4ced4a44dda5c7596c8c24043dbc-classes.dex"],nativeLibraryDirectories=[/data/app/com.bhtc.huajuan-2/lib/x86, /data/app/com.bhtc.huajuan-2/base.apk!/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libffmpeg.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:1076)
	at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:18)
	at org.wysaid.nativePort.CGEFrameRenderer.<clinit>(CGEFrameRenderer.java:11)
	at org.wysaid.view.CameraGLSurfaceView.onSurfaceCreated(CameraGLSurfaceView.java:413)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by forgekxf** [comment]
这是x86架构手机，其他手机上没有问题！

**Comment by wysaid** [comment]
@forgekxf 
了解， 下一个版本提供

**Comment by forgekxf** [comment]
多谢大师兄！！！下个版本大概什么时候呀~！

**Comment by wysaid** [comment]
这周末吧~

**Comment by forgekxf** [comment]
长时间录制编码有一点点卡顿，可以优化一下吗

**Comment by wysaid** [comment]
@forgekxf  你这个长时间是指多长时间呢。
一般来说机器录久了会发烫， 发烫的话CPU会降频散热， 所以会卡~

**Comment by forgekxf** [comment]
大师兄，希望尽快提供下 x86 so文件~~~

**Comment by wysaid** [comment]
@forgekxf  已提供~

**Comment by forgekxf** [comment]
没有看到呢~~~

**Comment by wysaid** [comment]
需要你编译一下 jni
```
export NDK=path/of/NDK
cd folder/of/jni
./buildJNI
```
即可

**Comment by wysaid** [comment]
🤔为了避免麻烦， 我把这些都编译一遍放出来了， 你更新下直接就有

**Comment by forgekxf** [comment]
嗯，刚刚测试了下，有一些问题~~~

**Comment by forgekxf** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.bhtc.huajuan-2/lib/x86/libffmpeg.so: has text relocations
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:1076)
	at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:18)
	at org.wysaid.nativePort.CGEFrameRenderer.<clinit>(CGEFrameRenderer.java:11)
	at org.wysaid.view.CameraGLSurfaceView.onSurfaceCreated(CameraGLSurfaceView.java:413)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by wysaid** [comment]
我倒是没有测试机…… 这个问题你可以把 app target 设定到 22 或者 22以下试试看
我再看看

**Comment by forgekxf** [comment]
嗯，target 设定到 22 确实没问题了~~~升级会有影响，不能覆盖安装了~

**Comment by wysaid** [comment]
把汇编代码去掉倒是可以先解决这个问题， 但是性能会下降， 我晚上再找找， 不行就先上一个无汇编代码的x86版本

**Comment by forgekxf** [comment]
好！

**Comment by Xiaomano** [comment]
你好，我想问一下，ios怎么集成您这个 框架，我用的时候编译总是出错

**Comment by wysaid** [comment]
@Xiaomano  参考demo呀

**Comment by Xiaomano** [comment]
你好，是这样的，我的xcode现在还是7，demo只能在xcode8上运行，我在xocde7上，把demo里的cge.framework还有.a文件拉进去。然后配置了搜索路径，但是编译总是通不过显示早不到cge这个框架

**Comment by wysaid** [comment]
@Xiaomano 
参考demo的build setting:
![http://i.imgur.com/lW2p1ND.png](http://i.imgur.com/lW2p1ND.png)

![http://i.imgur.com/vSxBiQn.png](http://i.imgur.com/vSxBiQn.png)

![http://i.imgur.com/oDCCARC.png](http://i.imgur.com/oDCCARC.png)

**Comment by forgekxf** [comment]
大师兄，能否先上一个无汇编代码的x86版本so呀！暂时只要不崩溃就行~

**Comment by wysaid** [comment]
@forgekxf OK， tonight

**Comment by wysaid** [comment]
done

**Comment by kam520c** [comment]
大圣，我拉你代码，加入了最新的x
86运行还是不行，报错，还差64位的so呢
```java
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kam-1/base.apk"],
nativeLibraryDirectories=[/data/app/com.kam-1/lib/arm64, /data/app/com.kam-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] 
couldn't find "libffmpeg.so"
```

**Comment by wysaid** [comment]
@kam520c 
arm64-v8a 也加进去了， 你们这些磨人的小妖精🙈
没有直接放到libs下面， 自己编译一下jni部分， 参考readme

**Comment by kam520c** [comment]
大师兄，不会编译呀，弄了一天都编译不出。。。

**Comment by wysaid** [comment]
下载 ndk-r10e 以上的版本
假设路径为  /xx/ndk 或 c:/xx/ndk
如果是 win下， 显然还需要cygwin, 并且你的目录为 /cygdrive/c/xx/ndk，
```
export NDK=/cygdrive/c/xx/ndk
cd /path/of/android-gpuimage-plus/library/src/main/jni
./buildJNI
```
别的环境下跟readme.md写的一样

**Comment by kam520c** [comment]
```java
kams-MacBook-Pro:android-gpuimage-plus kam$ export NDK=/Applications/adt-bundle-mac-x86_64-20140702/sdk/ndk-bundle
kams-MacBook-Pro:android-gpuimage-plus kam$ ls
README.md                       build                           cgedemo                         gradle                          gradlew                         library                         screenshots
android-gpuimage-plus.iml       build.gradle                    demoRelease                     gradle.properties               gradlew.bat                     local.properties                settings.gradle
kams-MacBook-Pro:android-gpuimage-plus kam$ cd library/src/main/jni
kams-MacBook-Pro:jni kam$ ./buildJNI
The NDK dir is: /Applications/adt-bundle-mac-x86_64-20140702/sdk/ndk-bundle, If the shell can not run normally, you should set the NDK variable to your local ndk-dir
Android NDK: ERROR:/Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni/Android.mk:ffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni/ffmpeg/armeabi/libffmpeg.so exists  or that its path is correct   
/Applications/adt-bundle-mac-x86_64-20140702/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```
我就是按你那个来的。不行

**Comment by wysaid** [comment]
不是都提示你了么， library/src/main/jni/ffmpeg/armeabi/libffmpeg.so 这个文件找不到
你确定你那个是最新的么， 请更新到最新

**Comment by kam520c** [comment]
是的，我更新到最新了
```java
kams-MacBook-Pro:~ kam$ ndk-build -C /Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni
make: Entering directory `/Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni'
[armeabi] Install        : libCGE.so => libs/armeabi/libCGE.so
[armeabi] Compile++ thumb: CGEExt <= cgeVideoUtils.cpp
In file included from /Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni/source/cgeVideoUtils.cpp:12:0:
/Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni/source/../interface/cgeFFmpegHeaders.h:13:32: fatal error: libavcodec/avcodec.h: No such file or directory
compilation terminated.
make: *** [/Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/obj/local/armeabi/objs/CGEExt//Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni/source/cgeVideoUtils.o] Error 1
make: Leaving directory `/Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni'
```
这个只能build出一个armeabi的libCGE.so文件，其他删掉了

**Comment by wysaid** [comment]
这个不是在提示你 libavcodec/avcodec.h 这个文件找不到嘛， 你找找？ 应该在 ffmpeg 目录下

**Comment by wysaid** [comment]
你真是逗比啊， 我发的消息你完全不看的？
我不是让你
```
export NDK=/path/to/ndk
./buildJNI
```
你当我逗你耍吗？ 说起话来真费劲

**Comment by kam520c** [comment]
用你那个还是提示ffmpeg: LOCAL_SRC_FILES points to a missing file 
```java
kams-MacBook-Pro:~ kam$ export NDK=/Applications/adt-bundle-mac-x86_64-20140702/sdk/android-ndk-r10b
kams-MacBook-Pro:~ kam$ cd Documents/workspace/android-gpuimage-plus/
kams-MacBook-Pro:android-gpuimage-plus kam$ ls
README.md                       build                           cgedemo                         gradle                          gradlew                         library                         screenshots
android-gpuimage-plus.iml       build.gradle                    demoRelease                     gradle.properties               gradlew.bat                     local.properties                settings.gradle
kams-MacBook-Pro:android-gpuimage-plus kam$ cd /library/src/main/jni
bash: cd: /library/src/main/jni: No such file or directory
kams-MacBook-Pro:android-gpuimage-plus kam$ cd library/src/main/jni
kams-MacBook-Pro:jni kam$ ./buildJNI
The NDK dir is: /Applications/adt-bundle-mac-x86_64-20140702/sdk/android-ndk-r10b, If the shell can not run normally, you should set the NDK variable to your local ndk-dir
Android NDK: ERROR:/Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni/Android.mk:ffmpeg: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni/ffmpeg/armeabi/libffmpeg.so exists  or that its path is correct   
/Applications/adt-bundle-mac-x86_64-20140702/sdk/android-ndk-r10b/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```

**Comment by wysaid** [comment]
Android NDK: Check that /Users/kam/Documents/workspace/android-gpuimage-plus/library/src/main/jni/ffmpeg/armeabi/libffmpeg.so exists  or that its path is correct
先看看这个文件在不在吧。

**Comment by wysaid** [comment]
所有的arch现在都在libs目录下有编译好的， 你可以直接使用了。

**Comment by kam520c** [comment]
还是不行哦，大师兄，arm64-v8a缺失
```java
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kam-2/base.apk"],
nativeLibraryDirectories=[/data/app/com.kam-2/lib/arm64, /data/app/com.kam-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libffmpeg.so"
```
然后我找了你的文件，最新的代码中/jni/cge/arm64-v8a 里有个libCGE.so，/jni/ffmpeg/arm64-v8a下有个libffmpeg.so 然后把两个都拷出来，还缺少libCGEExt.so和libFaceTracker.so，这两个就找不到64位的了

**Comment by wysaid** [comment]
更新到最新， library/src/main/libs 下面有我编译好的， 你不用折腾了

**Comment by kam520c** [comment]
嗯嗯，我已经成功跑起来了，太感谢大师兄了。之前是一直兼容不了最新出的安卓手机，都是64位的，现在搞掂了

**Comment by wysaid** [comment]
😬

**Comment by wysaid** [comment]
libFaceTracker.so 不是必须的， 不用的话可以直接扔掉

**Comment by kam520c** [comment]
好的

**Comment by forgekxf** [comment]
大师兄，我发现录制出来的视频，稍微有点视频、音频不同步的感觉，音频是不是有点滞后了~~~

**Comment by forgekxf** [comment]
大师兄，低配手机上，录制的视频会有卡顿的现象
