### ISSUE TITLE
Split Toning

### ISSUE THREAD

**Issue by jeetdholakia** [wysaid/android-gpuimage-plus#273]
Can we have separate colors for shadows and highlights? From CGE-Generator I cannot see any option to select color...

Thanks

**Comment by wysaid** [comment]
If the builtin effects can not match your requirements, you may need to write a custom filter.

**Comment by jeetdholakia** [comment]
Okay, generally in HSL you can select Blue, Cyan, etc. Maybe we will see it in future updates 👍

**Comment by wysaid** [comment]
If you're saying the `select color` adjust, it's already in the `filter-generator`.
Please see [this](https://github.com/wysaid/android-gpuimage-plus/wiki/Parsing-String-Rule-En#6-selcolor)
