### ISSUE TITLE
关于动态贴图滤镜请教

### ISSUE THREAD

**Issue by yungs2017** [wysaid/android-gpuimage-plus#274]
最近在做人脸的动态贴图，其中遇到一个问题想请教下。
假如我的动态贴图中需要对人脸的唇彩进行处理（已经定位出来关键点），是否可以使用滤镜来进行实现？还是需要处理一份嘴唇的纹理图片贴上去？

**Comment by wysaid** [comment]
当然可以滤镜实现
不过你需要自己连接顶点三角形序列， 最后用 GL_TRIANGLES 之类的方式直接绘制上去。
像你的需求， 需要把嘴部的几个或者十几个点连成mesh往上话， 不能用 handler 传过来的全屏顶点

**Comment by yungs2017** [comment]
就是利用嘴唇的标点数据构建顶点然后更改里面的颜色来实现吗？

**Comment by wysaid** [comment]
不仅仅是改颜色哦， 一般来说做妆容的话， 你是设计一个lookup 专门处理嘴巴
即， 先把整张脸纹理原封不动绘制到target fbo， 然后再把这个输入纹理以及专用的lookup以及素材图片等用你的mesh绘制一遍， 这个mesh只绘制嘴巴的区域， 所以只对嘴巴做lookup和贴图。 这个高光素材也应该是一个嘴巴的形状， 并具标记了跟嘴巴一一对应的关键点， 可以完整映射
