### ISSUE TITLE
Cannot load library: reloc_library[1285]: 117 cannot locate 'posix_memalign'... 

### ISSUE THREAD

**Issue by jeffersonlicet** [wysaid/android-gpuimage-plus#280]
Android : 4.0.4 

Failed when trying to start library.
im using: org.wysaid:gpuimage-plus:2.4.10

```
org.wysaid.nativePort.NativeLibraryLoader.load (NativeLibraryLoader.java:18)
org.wysaid.nativePort.CGENativeLibrary.<clinit> (CGENativeLibrary.java:18)
net.sparkly.pixely.processors.FilterProcessor.initLibrary (FilterProcessor.java:146)
```

Thank you.

**Comment by wysaid** [comment]
What is the error or the exception?
I can't see the error msg.

**Comment by jeffersonlicet** [comment]
Exception: java.lang.ExceptionInInitializerError 
Caused by: Cannot load library: reloc_library[1285]: 117 cannot locate 'posix_memalign'... 
those are the messages that firebase displays. Thank you.

**Comment by wysaid** [comment]
https://stackoverflow.com/questions/27338318/cannot-load-library-reloc-library1285-cannot-locate-rand
It seems like a common problem. Maybe you can solve that follow the answer?
