### ISSUE TITLE
Permanent and preview video filter is different.

### ISSUE THREAD

**Issue by usmankhan495** [wysaid/android-gpuimage-plus#281]
Hi,
I have applied contrast filter on video.For example If I set the contrast value 2 and apply this config on video for preview and generate the video using this function generateVideoWithFilter(); with same config string, but the output video is little bit different.Please help me.
Thanks

**Comment by wysaid** [comment]
The video compression will lose some quality.
And the yuv color format will also drop the color precision.
If you're not sure if it is a bug, you can post your video here. I will check it.

**Comment by usmankhan495** [comment]
Thanks for your quick response.
Here is video link.
https://www.dropbox.com/s/xzgmkjrpdf8tb9m/video.mp4?dl=0
I also want to apply more than one filter (contrast,brightness,saturation) at a time.There is not such method for video surface that changes value at index like this setFilterIntensityForIndex()  for image surface.
Thanks

**Comment by wysaid** [comment]
I see. But I can't find your problem.
The rule string can be merged.
If you want more than one filter, just pass them. "@adjust contrast ... @adjust brightness ..."

**Comment by usmankhan495** [comment]
This is my problem.Please see the attached image.
![videoeffect](https://user-images.githubusercontent.com/9165961/35082060-907a9978-fc39-11e7-8295-d72247c3c805.png)

I have applied contrast value 2 using rule string for preview and permanent effect.

**Comment by wysaid** [comment]
Please paste your rule string here, and I will test it on my device.

**Comment by usmankhan495** [comment]
String config="@adjust brightness "+value+" @adjust contrast "+value+" @adjust saturation "+value;
I am using this string.I am setting value according to user input.
Thanks

**Comment by usmankhan495** [comment]
I have also tested for only one rule like @adjust contrast 2.

**Comment by usmankhan495** [comment]
I have another issue If I apply video filter more than one time the output file drop the last video frames.Need you help.
Thanks

**Comment by wysaid** [comment]
Hi, I changed the [yuv convert matrix](https://developer.apple.com/library/content/samplecode/GLCameraRipple/Listings/GLCameraRipple_Shaders_Shader_fsh.html#//apple_ref/doc/uid/DTS40011222-GLCameraRipple_Shaders_Shader_fsh-DontLinkElementID_9)
But the result is still  a little different.
Maybe you can try other ones which looks better.

**Comment by usmankhan495** [comment]
Hi 
Thanks you very much for helping this issue.Now this issue is almost solved and my other issue which was green line issue on right side of video has also been solved by increasing the width of video.
Thanks again

**Comment by anu30** [comment]
Hi Wysaid,

How to apply brightness, contrast, saturation and sharpen effects along with lut filters to videos? 
I used `@adjust brightness 0 @adjust contrast 1 @adjust saturation 1 @adjust sharpen 0 @adjust lut aquaholic.jpg`  to add multiple filters to images. How to do the same for videos?

**Comment by anu30** [comment]
Hi @usmankhan495 

How did you resolve this issue? I also applied these filters using @adjust brightness +value @adjust contrast +value @adjust saturation +value @adjust sharpen +value @adjust lut aquaholic.jpg, but I am also seeing preview video and generated video bit different. 
Can you please help me with this issue?

**Comment by anu30** [comment]
You can use different sliders to take different ranges of each filter. 
I have used below mentioned ranges based on my requirement, but you can try out with some modifications:
(-1.0f, 1.0f) //brightness
(0.1f, 3.0f) //contrast
(0.0f, 3.0f) //saturation

**Comment by AnitaVPN** [comment]
Thanks @anu30 for your reply

I took three slider for each brightness , contrast , saturation and set value accordingly , now the diffrent issue i am getting is when saving video , the video quality loss

How to save video with high quality ?

**Comment by AnitaVPN** [comment]
Hello @usmankhan495  @wysaid  @anu30  i want to implement the functionality of adjusting brightness contrast saturation of a video and resetting back the video to its original state when sliders are brought back at center. In the git hub source code this functionality is present in a class named as "BasicImageDemoActivity" but for image and not for video. 

Anyone, having worked on this or have any idea about this, please help me.
Your help will be really appreciated.
