### ISSUE TITLE
ImageGLSurfaceView scaletype?

### ISSUE THREAD

**Issue by jeetdholakia** [wysaid/android-gpuimage-plus#283]
Hi,

I am not able to display the image according to its correct ratio, would I have to programmatically change the dimensions of the image before displaying it?  

It would be convenient if the image view supported scaletype like matrix, centercrop...etc.

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/java/org/wysaid/view/ImageGLSurfaceView.java#L31

**Comment by jeetdholakia** [comment]
Thanks a lot for that
