### ISSUE TITLE
How to store different LUT/ Filters in different folders

### ISSUE THREAD

**Issue by jeetdholakia** [wysaid/android-gpuimage-plus#284]
Hi,

I can only access them if they're stored in assets root folder, if I create a child folder inside assets, the filter does not work...

**Comment by wysaid** [comment]
You can change the loadImageCallback, and set to any folder.

**Comment by jeetdholakia** [comment]
Okay, but that solves the problem of having all of LUT in 1 folder, I have a structure like VSCO, 5 types of filter categories, and 10 filters (LUT) in each of them, so I kept a folder for every category, I think it helps with my recyclerview adapter because I just have to point it to any folder onClick, so do you suggest that I create more than 1 `CGENativeLibrary.LoadImageCallback`, is it a good implementation?

**Comment by jeetdholakia** [comment]
Thanks, I think I will parse the name string and search inside assets from same loadImageCallback, I appreciate the help

**Comment by wysaid** [comment]
you can write the filter with folder name
e.g.: `@adjust lut dirxxx/lookup.png`

**Comment by jeetdholakia** [comment]
yes, I'm sorry I used the sample application provided CGEDemo and it was my error in giving the correct path to the callback... but thanks for the help

**Comment by wysaid** [comment]
😬
