### ISSUE TITLE
Wont play video on some phones - error (1, -19)

### ISSUE THREAD

**Issue by amiga** [wysaid/android-gpuimage-plus#287]
Some phones wont play video some stop workign aftr it has looped a few times, mostly sony z5 and zamsung s6. Get MEDIA-STATE_ERROR and sometimes media error -19.

**Comment by amiga** [comment]
02-02 15:18:20.125 6138-6138/com.chunkgroup.cbbcnow D/SurfaceView: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2560] result=0x7 surface={Surface(name=null)/@0xf87ab08 isValid=true -967772160}
02-02 15:18:20.139 6138-7054/com.chunkgroup.cbbcnow D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
02-02 15:18:20.140 6138-7054/com.chunkgroup.cbbcnow I/libCGE_java: video player onSurfaceCreated...
02-02 15:18:20.154 6138-7054/com.chunkgroup.cbbcnow V/MediaPlayer-JNI: native_setup
02-02 15:18:20.154 6138-7054/com.chunkgroup.cbbcnow V/MediaPlayer: constructor
02-02 15:18:20.154 6138-7054/com.chunkgroup.cbbcnow V/MediaPlayer: setListener
02-02 15:18:20.165 6138-7054/com.chunkgroup.cbbcnow D/RingtoneManager: Can’t get current user. return default user
02-02 15:18:20.165 6138-7054/com.chunkgroup.cbbcnow V/MediaPlayer-JNI: setDataSourceFD: fd 125
02-02 15:18:20.165 6138-7054/com.chunkgroup.cbbcnow V/MediaPlayer: setDataSource(125, 0, 576460752303423487)
02-02 15:18:20.168 6138-7054/com.chunkgroup.cbbcnow V/MediaPlayer: setVideoSurfaceTexture
02-02 15:18:20.169 6138-7054/com.chunkgroup.cbbcnow V/MediaPlayer: setVideoSurfaceTexture
02-02 15:18:20.170 6138-7054/com.chunkgroup.cbbcnow V/MediaPlayer: prepareAsync
02-02 15:18:20.171 6138-7054/com.chunkgroup.cbbcnow I/libCGE_java: View port: 0, 560, 1440, 1440
02-02 15:18:20.205 6138-6151/com.chunkgroup.cbbcnow V/MediaPlayer: message received msg=5, ext1=540, ext2=540
02-02 15:18:20.205 6138-6151/com.chunkgroup.cbbcnow V/MediaPlayer: New video size 540 x 540
02-02 15:18:20.205 6138-6151/com.chunkgroup.cbbcnow V/MediaPlayer: callback application
02-02 15:18:20.205 6138-6151/com.chunkgroup.cbbcnow V/MediaPlayer: back from callback
02-02 15:18:20.207 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: message received msg=1, ext1=0, ext2=0
02-02 15:18:20.207 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: prepared
02-02 15:18:20.207 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: callback application
02-02 15:18:20.207 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: back from callback
02-02 15:18:20.218 6138-6138/com.chunkgroup.cbbcnow D/MyApp: PaintWithFingerActivity#######FILES permissiosn timer a
02-02 15:18:20.227 6138-6138/com.chunkgroup.cbbcnow D/SurfaceView: Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={Surface(name=null)/@0xf87ab08 isValid=true -789311488}
02-02 15:18:20.230 6138-6138/com.chunkgroup.cbbcnow D/MediaPlayer: setSubtitleAnchor in MediaPlayer
02-02 15:18:20.233 6138-6138/com.chunkgroup.cbbcnow V/MediaPlayer: invoke 68
02-02 15:18:20.237 6138-6138/com.chunkgroup.cbbcnow V/MediaPlayer: getVideoWidth
02-02 15:18:20.237 6138-6138/com.chunkgroup.cbbcnow V/MediaPlayer-JNI: getVideoWidth: 540
02-02 15:18:20.237 6138-6138/com.chunkgroup.cbbcnow V/MediaPlayer: getVideoHeight
02-02 15:18:20.237 6138-6138/com.chunkgroup.cbbcnow V/MediaPlayer-JNI: getVideoHeight: 540
02-02 15:18:20.239 6138-6138/com.chunkgroup.cbbcnow I/libCGE_java: Video resolution 1: 540 x 540
02-02 15:18:20.246 6138-6138/com.chunkgroup.cbbcnow D/MyApp: PaintWithFingerActivity#######! Start playing ->> /data/user/0/com.chunkgroup.cbbcnow/app_cbbcbuzz_internal/video.mp4
02-02 15:18:20.248 6138-6138/com.chunkgroup.cbbcnow V/MediaPlayer-JNI: start
02-02 15:18:20.249 6138-6138/com.chunkgroup.cbbcnow V/MediaPlayer: start
02-02 15:18:20.256 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: message received msg=300, ext1=0, ext2=0
02-02 15:18:20.258 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: Received SEC_MM_PLAYER_CONTEXT_AWARE
02-02 15:18:20.258 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: callback application
02-02 15:18:20.259 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: back from callback
02-02 15:18:20.276 6138-7054/com.chunkgroup.cbbcnow I/libCGE: registerFFmpeg...
02-02 15:18:20.276 6138-7054/com.chunkgroup.cbbcnow I/libCGE: ===== Here are some information of your device =====
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: GL_INFO Vendor = ARM
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: GL_INFO Renderer = Mali-T760
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: GL_INFO GL Version = OpenGL ES 3.2 v1.r15p0-00rel0.68b65ac7cf15907aeb95fa944f39eef2
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: GL_INFO GL Extension = GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EX
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: GL_INFO Shading Language Version = OpenGL ES GLSL ES 3.20
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Max Vertex Uniform Vectors: 1024
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Max Fragment Uniform Vectors : 1024
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Max Varying Vectors: 15
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Max Texture Image Units : 16
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Max Combined Texture Image Units : 96
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Max Texture Size : 8192
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Max Vertex Attribs: 16
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Max Viewport Dims : [8192, 8192]
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Max Render Buffer Size: 8192
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Stencil Buffer Bits : 0
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Point Size Range: [1, 1024]
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Line Width Range: [1, 4096]
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Depth Bits: 24
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: ===== Information end =====
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: native instance address: 0xc7020650
02-02 15:18:20.277 6138-7054/com.chunkgroup.cbbcnow I/libCGE: CGEFrameRenderer::init...
02-02 15:18:20.302 6138-7054/com.chunkgroup.cbbcnow I/libCGE: create cache texture: 540 x 540
02-02 15:18:20.303 6138-7054/com.chunkgroup.cbbcnow I/libCGE: CGEFrameRenderer - viewport: 0, 0, 540, 540
02-02 15:18:20.303 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Image Handler Init With RawBufferData 540 x 540, 4 channel
02-02 15:18:20.303 6138-7054/com.chunkgroup.cbbcnow I/libCGE: Vertex Array Buffer id: 4
02-02 15:18:20.303 6138-7054/com.chunkgroup.cbbcnow I/libCGE: FBO buffer texture id: 2 and 3
02-02 15:18:20.303 6138-7054/com.chunkgroup.cbbcnow I/libCGE: FBO Framebuffer id: 1
02-02 15:18:20.304 6138-7054/com.chunkgroup.cbbcnow I/libCGE_java: View port: 0, 560, 1440, 1440
02-02 15:18:20.373 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: message received msg=300, ext1=0, ext2=0
02-02 15:18:20.374 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: Received SEC_MM_PLAYER_CONTEXT_AWARE
02-02 15:18:20.374 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: callback application
02-02 15:18:20.375 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: back from callback
02-02 15:18:20.375 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: message received msg=100, ext1=1, ext2=-19
02-02 15:18:20.375 6138-6234/com.chunkgroup.cbbcnow E/MediaPlayer: error (1, -19)
02-02 15:18:20.375 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: callback application
02-02 15:18:20.376 6138-6138/com.chunkgroup.cbbcnow E/MediaPlayer: Error (1,-19)
02-02 15:18:20.376 6138-6234/com.chunkgroup.cbbcnow V/MediaPlayer: back from callback
02-02 15:18:20.376 6138-6138/com.chunkgroup.cbbcnow D/MyApp: PaintWithFingerActivity#######FAILED TO PLAY VIDEO
02-02 15:18:20.376 6138-6138/com.chunkgroup.cbbcnow D/MyApp: Tools#######TOAST MESSAGE ------------>cant play video 1... -19
                                                             
                                                             [ 02-02 15:18:20.376  3139: 7144 I/         ]
                                                             SAACD_COMP_Reset() in
02-02 15:18:20.427 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@e706fb4[Toast]: ThreadedRenderer.create() translucent=true
02-02 15:18:20.437 6138-6138/com.chunkgroup.cbbcnow D/InputTransport: Input channel constructed: fd=127
02-02 15:18:20.437 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@e706fb4[Toast]: setView = android.widget.LinearLayout{12097dd V.E...... ......I. 0,0-0,0} touchMode=true
02-02 15:18:20.438 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@e706fb4[Toast]: dispatchAttachedToWindow
02-02 15:18:20.471 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: message received msg=5, ext1=540, ext2=540
02-02 15:18:20.471 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: New video size 540 x 540
02-02 15:18:20.471 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: callback application
02-02 15:18:20.471 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: back from callback
02-02 15:18:20.471 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: message received msg=200, ext1=3, ext2=0
02-02 15:18:20.471 6138-6152/com.chunkgroup.cbbcnow W/MediaPlayer: info/warning (3, 0)
02-02 15:18:20.471 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: callback application
02-02 15:18:20.471 6138-6152/com.chunkgroup.cbbcnow V/MediaPlayer: back from callback
02-02 15:18:20.483 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@e706fb4[Toast]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[332,2128][1107,2304] result=0x27 surface={isValid=true -1062062080} surfaceGenerationChanged=true
02-02 15:18:20.485 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@e706fb4[Toast]: mHardwareRenderer.initialize() mSurface={isValid=true -1062062080} hwInitialized=true
02-02 15:18:20.487 6138-6212/com.chunkgroup.cbbcnow D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [775x176]-format:1
02-02 15:18:20.488 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@e706fb4[Toast]: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
02-02 15:18:20.490 6138-7054/com.chunkgroup.cbbcnow E/MediaPlayer: isPlaying: called in state MEDIA_PLAYER_STATE_ERROR
02-02 15:18:22.426 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@e706fb4[Toast]: mHardwareRenderer.destroy()#4
02-02 15:18:22.426 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@e706fb4[Toast]: dispatchDetachedFromWindow
02-02 15:18:22.435 6138-6138/com.chunkgroup.cbbcnow D/InputTransport: Input channel destroyed: fd=127
02-02 15:18:22.610 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@18fe8b5[PaintWithFingerActivity]: ViewPostImeInputStage processPointer 0
02-02 15:18:22.678 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@18fe8b5[PaintWithFingerActivity]: ViewPostImeInputStage processPointer 1
02-02 15:18:22.678 6138-6138/com.chunkgroup.cbbcnow D/MyApp: PaintWithFingerActivity#######ibSkip tapped on tut
02-02 15:19:23.023 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@18fe8b5[PaintWithFingerActivity]: MSG_WINDOW_FOCUS_CHANGED 0
02-02 15:19:23.025 6138-6138/com.chunkgroup.cbbcnow D/MyApp: PaintWithFingerActivity#######onPause
02-02 15:19:23.025 6138-6138/com.chunkgroup.cbbcnow E/MediaPlayer: isPlaying: called in state MEDIA_PLAYER_STATE_ERROR
02-02 15:19:23.110 6138-6138/com.chunkgroup.cbbcnow D/MyApp: PaintWithFingerActivity#######onSystemUiVisibilityChange
02-02 15:19:23.135 6138-6138/com.chunkgroup.cbbcnow D/SurfaceView: Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={Surface(name=null)/@0xf87ab08 isValid=false 0}
02-02 15:19:23.139 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@18fe8b5[PaintWithFingerActivity]: mHardwareRenderer.destroy()#1
02-02 15:19:23.145 6138-6138/com.chunkgroup.cbbcnow D/ViewRootImpl@18fe8b5[PaintWithFingerActivity]: Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
02-02 15:19:23.161 6138-6138/com.chunkgroup.cbbcnow D/MyApp: PaintWithFingerActivity#######onSystemUiVisibilityChange

**Comment by wysaid** [comment]
Did this happen on the builtin demo?
If not, you may need to search your problem with `Google` or `Stackoverflow`.
Playing video is based on `MediaPlayer`, and `MediaPlayer` is a android standard class for multimedia.

**Comment by amiga** [comment]
My tester confirms it does not happen on the demo, I based my code on it, but I must have done something wrong, will check my code again. I think I forgot .release in onpause.

**Comment by amiga** [comment]
Fixed I forgot .release. Thanks.

**Comment by amiga** [comment]
Actually this still happens with all the correct calls in, no idea why cannot find the issue. Often -19 error on s6 and z5
