### ISSUE TITLE
在华为Mate7上截取视频画面黑屏

### ISSUE THREAD

**Issue by shazha** [wysaid/android-gpuimage-plus#29]
你好！
我用您的代码在安卓机器上进行视频录制，当在华为Mate7上测试时，可以播放视频以及给视频加滤镜，但是无法通过VideoPlayerGLSurfaceView中的takeshot方法截图，在其他安卓机器上则没有问题。我debug发现GLES20.glReadPixels方法执行之后的IntBuffer的像素值全是0。在您提供的demo release的apk中也可以复现这问题。您是否方便验证下这是否是个bug？

**Comment by wysaid** [comment]
好的~
我暂时没有测试机， 下个版本之前我会找一个验证并修改下
