### ISSUE TITLE
Version Difference between Libraries?

### ISSUE THREAD

**Issue by jeetdholakia** [wysaid/android-gpuimage-plus#293]
I switched from the first one to the second one and my apk size is now much smaller, which was the goal, but I am not sure why the version number is older? Does it miss any patch, bug or fix? I do not need FFMPEG but I want to make sure 2.4.6 is as stable as 2.4.10...

```
dependencies {
    //All arch: armeabi, armeabi-v7a, arm64-v8a, mips, x86
    compile 'org.wysaid:gpuimage-plus:2.4.10'
    

    //Pure graphics lib without ffmpeg. (all arch for branch 'min')
    compile 'org.wysaid:gpuimage-plus:2.4.6-min'
}
```

**Comment by wysaid** [comment]
Sorry for the late reply.
Both versions are right.
The version  `org.wysaid:gpuimage-plus:2.4.10`  is higher because of bug fixing of the video recording module. But the other one did not include that feature, so its version keeps `2.4.6`

**Comment by jeetdholakia** [comment]
Thanks a lot, it's helpful
