### ISSUE TITLE
Intensity not set on captured picture

### ISSUE THREAD

**Issue by iffatfatima** [wysaid/android-gpuimage-plus#299]
If you change the intensity after applying the filter, the captured picture does not have that intensity applied on its filter. I am using this: `myGLSurfaceView.setFilterIntensity(intensity);`
Demo app shows the same behavior as well. Is there any way to fix this?_

**Comment by Ashutosh-Tiwari** [comment]
@iffatfatima I don't know if you are following the correct way. But once you have got the captured image, you first need to apply the filter using filter `config` string using 'setFilterWithConfig(filterSttring)'. Then you can use `setFilterIntensity(intensity)` to show a visual application of the filter intensity.

Once the filter is final and you need the image, you need to process the filter to actually execute it's application on the image. For that look for methods like `processFilters()`, `getResultBitmap()` in the demo app.
Take a note, `setFilterIntensity()` method doesn't actually apply the filter on the image and that application is only for the display to see how the filter looks.
Correct me if M wrong @wysaid

**Comment by iffatfatima** [comment]
@Ashutosh-Tiwari the scenario you are explaining is different. In my case I wanted to apply the intensity at the time of capturing picture. You are right about `setFilterIntensity( )` though. The library actually provides the functionality that I was looking for, I clearly missed it before. For anyone looking, you can pass the filter intensity as an argument to the takePicture method. 
`    public synchronized void takePicture(final TakePictureCallback photoCallback, Camera.ShutterCallback shutterCallback, final String config, final float intensity, final boolean isFrontMirror) {`
