### ISSUE TITLE
可以用视频文件当滤镜吗？

### ISSUE THREAD

**Issue by zhaodaizheng** [wysaid/android-gpuimage-plus#3]
可以用视频文件当滤镜吗？同时播放两个视频，类似于视频融合

**Comment by wysaid** [comment]
当然可以， 请参照播放器， 新建一个MediaPlayer, 增加一个 SurfaceTexture， 我还封装了几个渲染单张Texture的类， 你参考一下， 重新写一个 TextureDrawer， 输入变成两张纹理， 然后自己处理一下blend就行， 请自己实现一下哈
