### ISSUE TITLE
How can i set backgrount with white in ImageGLSurfaceView

### ISSUE THREAD

**Issue by ash3734** [wysaid/android-gpuimage-plus#302]
I set image by ImageGLSurfaceView.setImageBitmap method. My bitmap size is variable. So in my app the ImageGLSurfaceView's margin's color is black. I want to change this color to white.
plz help me my ploblem ...

**Comment by GoGoing2101** [comment]
Hi. I just implement the version 'org.wysaid:gpuimage-plus:2.6.3' but it does not contain the code that makes the ImageGLSurfaceView transparency. Please help.

**Comment by CassieKillsIt** [comment]
Your update is exactly what I did @GoGoing2101. Wysaid merged my changes. but removed the line that actually fixed this issue for me.

**Comment by wysaid** [comment]
> Your update is exactly what I did @GoGoing2101. Wysaid merged my changes. but removed the line that actually fixed this issue for me.

Oh... You mean this: https://github.com/wysaid/android-gpuimage-plus/pull/322
The setting will break  the view layout.  So maybe we can make a comment at that position. Any one can use it if needed.

**Comment by GoGoing2101** [comment]
Hi @CassieKillsIt, @wysaid ,

I successfully make the background transparent. But if I make the deform in the edge of the image and save it to the device, now the image that was exported has a black background in the place that was deformed. There is any way to save the image with a transparent background?

**Comment by wysaid** [comment]
> Hi @CassieKillsIt, @wysaid ,
> 
> I successfully make the background transparent. But if I make the deform in the edge of the image and save it to the device, now the image that was exported has a black background in the place that was deformed. There is any way to save the image with a transparent background?

Sure， you must save your image with `png` format.  Now it's saving as `jpg`.  Maybe you can get the right result with the `png` format.

**Comment by GoGoing2101** [comment]
> > Hi @CassieKillsIt, @wysaid ,
> > I successfully make the background transparent. But if I make the deform in the edge of the image and save it to the device, now the image that was exported has a black background in the place that was deformed. There is any way to save the image with a transparent background?
> 
> Sure， you must save your image with `png` format. Now it's saving as `jpg`. Maybe you can get the right result with the `png` format.

Hi @wysaid ,
I already save the bitmap as ".PNG" but no luck, the background still black after saved :(

**Comment by wysaid** [comment]
> > > Hi @CassieKillsIt, @wysaid ,
> > > I successfully make the background transparent. But if I make the deform in the edge of the image and save it to the device, now the image that was exported has a black background in the place that was deformed. There is any way to save the image with a transparent background?
> > 
> > 
> > Sure， you must save your image with `png` format. Now it's saving as `jpg`. Maybe you can get the right result with the `png` format.
> 
> Hi @wysaid ,
> I already saved the bitmap as ".PNG" but no luck, the background still black after saved :(

Please check the background color and the OpenGL clear color. Make sure it is set to rgba(0,0,0,0)
