### ISSUE TITLE
How to use a texture bitmap from url?

### ISSUE THREAD

**Issue by jeetdholakia** [wysaid/android-gpuimage-plus#303]
I want to use AWS to move all my png files and do not want to download them, just want to use the URL, how do I do that?

**Comment by wysaid** [comment]
It's an Android programming issue, you should download your urls, and convert to Bitmaps.

You can setup a table which marks every filter with its resource. When you use anyone, download the resource first.

**Comment by jeetdholakia** [comment]
Thanks, I thought putting a url in load image method might work, similar to glide...
