### ISSUE TITLE
What does style min max do?

### ISSUE THREAD

**Issue by jeetdholakia** [wysaid/android-gpuimage-plus#306]
I read the documentation in both languages but could not figure it out...help is appreciated...

**Comment by wysaid** [comment]
Please see this: https://www.graphicsmill.com/docs/gm/minimum-maximum-median-filters.htm#Noise

Or you can search like: https://www.google.com.sg/search?q=min+value+filter&oq=min+value+filter&aqs=chrome..69i64j0j69i57.7245j0j7&sourceid=chrome&ie=UTF-8

**Comment by jeetdholakia** [comment]
Thanks, it helped understand some concepts!
