### ISSUE TITLE
应用滤镜时经常闪退（非必现）：JNI DETECTED ERROR IN APPLICATION

### ISSUE THREAD

**Issue by hanswimtj** [wysaid/android-gpuimage-plus#312]
错误信息：
art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: thread Thread[1,tid=2578,Native,Thread*=0xaac51a60,peer=0x73bbef10,"main"] using JNIEnv* from thread Thread[1,tid=2578,Native,Thread*=0xaac51a60,peer=0x73bbef10,"main"]
art/runtime/java_vm_ext.cc:410]     in call to GetStaticMethodID
art/runtime/java_vm_ext.cc:410]     from android.graphics.Bitmap org.wysaid.nativePort.CGENativeLibrary.cgeFilterImage_MultipleEffects(android.graphics.Bitmap, java.lang.String, float)
art/runtime/java_vm_ext.cc:410] "main" prio=5 tid=1 Runnable
art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x73bbef10 self=0xaac51a60
art/runtime/java_vm_ext.cc:410]   | sysTid=2578 nice=-1 cgrp=top_visible sched=0/0 handle=0xf7560b38
art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 5816599776 145311296 4434 ) utm=530 stm=51 core=5 HZ=100
art/runtime/java_vm_ext.cc:410]   | stack=0xff485000-0xff487000 stackSize=8MB
art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
art/runtime/java_vm_ext.cc:410]   at org.wysaid.nativePort.CGENativeLibrary.cgeFilterImage_MultipleEffects(Native method)
art/runtime/java_vm_ext.cc:410]   at org.wysaid.nativePort.CGENativeLibrary.filterImage_MultipleEffects(CGENativeLibrary.java:130)

请问这个错误是啥意思啊？多谢！

**Comment by wysaid** [comment]
这个错误是自带的demo里面出现的还是你们这边自己做的app出现的？

**Comment by hanswimtj** [comment]
@wysaid 我自己的app里面的。我有一个滤镜预览页面，需要对同一张缩略图同时应用多个滤镜给用户选择，就是这个时候经常出错。

**Comment by wysaid** [comment]
Simple Demo Case 那个按钮下有类似的使用场景， 你参考下吧

**Comment by hanswimtj** [comment]
@wysaid 似乎不太一样，Demo里是点一下按钮应用一个滤镜效果，我的应用是进入滤镜页面时立刻应用多个不同的滤镜进行预览。我尝试了在每次应用滤镜之前加一个`SystemClock.sleep(50);`，发现程序崩溃的概率大幅下降，很奇怪。

**Comment by wysaid** [comment]
你可以fork一份， 在内置的demo里面复现一下你的问题， 然后给个链接我帮你看看

**Comment by evichrock** [comment]
@hanswimtj Have you solved the issue? I have the same here, I have a list of static preview images and I apply filters on them for filter previewing purpose. For more info, I'm using Glide to load images asynchronously and apply filters using bitmapTransform.

**Comment by evichrock** [comment]
@wysaid When I'm not using bitmapTransform (I think multi-threading cause crashing) and use a Executors.newSingleThreadExecutor() to apply filter with only one thread synchronously then it doesn't crash any more but the trade off is I can't get benefits from Glide (caching, multi-threading).

**Comment by hanswimtj** [comment]
@evichrock Not solved. I added a long delay(100ms) after calling `filterImage_MultipleEffects`, although this would have a very bad user experience.

**Comment by wysaid** [comment]
@evichrock @hanswimtj  Fixed in the latest `master` branch

**Comment by wysaid** [comment]
I will update the maven repo today

**Comment by wysaid** [comment]
Maven repo updated, please use version `org.wysaid:gpuimage-plus:2.5.1*`

**Comment by hanswimtj** [comment]
Great work! Problem solved now!

**Comment by evichrock** [comment]
@wysaid Greate work! Thank you

**Comment by hanswimtj** [comment]
@wysaid Thanks a lot!
