### ISSUE TITLE
滤镜叠加问题

### ISSUE THREAD

**Issue by qq297110281** [wysaid/android-gpuimage-plus#316]
非常好的项目，很有借鉴意义。
最近在做一个项目碰到一个问题，想请教一下，具体的问题如下：
项目中有一项功能是 对视频画面进行缩放，同时又要叠加多个滤镜 比如：饱和度、亮度、对比度。对于缩放功能我使用了GPUImageTransformFilter [实现了缩放功能（设置缩放矩阵）但是当同时叠加其他滤镜（如上所述）如果缩放后画面是缩小（保留全部画面，surface上面存在黑边）surface上面的黑边由于应用了其他的叠加滤镜，在一些机型上面会有频闪的细线，具体如截图：
[http://resource.snoppa.com/web/images/20180418/bug-videoedit.jpg](url)
想请教一下有没有解决方案？？

**Comment by wysaid** [comment]
每一帧之前用glClear清屏一下吧

**Comment by qq297110281** [comment]
每一帧都已经清屏（代码：GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT | GLES20.GL_DEPTH_BUFFER_BIT)），但是结果还是跟截图一样。猜测应该是 后面叠加的滤镜渲染范围是整个surface导致的。

**Comment by qq297110281** [comment]
后面解决了，在后面添加的最后一个滤镜加上缩放矩阵就行了，其余滤镜一律加缩放矩阵
