### ISSUE TITLE
ffmpeg库冲突

### ISSUE THREAD

**Issue by bookzhan** [wysaid/android-gpuimage-plus#33]
目前我们引用了一个第三方库也叫libffmpeg.so,这样就和您这个库冲突了,您能把libffmpeg.so重命名, 然后编译一下libCGE.so吗? 多谢了

**Comment by wysaid** [comment]
共用一个不行？

**Comment by bookzhan** [comment]
不行,他的库不是原生编译的,加了一些函数,所以拜托了

**Comment by wysaid** [comment]
那就用他那个

**Comment by wysaid** [comment]
同样的库， 包含重名的符号， 就像你不能在两个不同文件定义相同名字的全局函数（不加static)
改了名字也无济于事， 你要么用我用到这个， 要么用他编译的那个， 如果他编译的那个版本有我这边用到的符号的话， 也是能跑的， 懂了吗~

**Comment by bookzhan** [comment]
这个我知道,但是用他的库跑, 很多功能都用不了,报错如下:E/libCGE: Could not find encoder for 'mpeg2video'

**Comment by wysaid** [comment]
你知道有这个问题还把so发给我让我编译？
他编译的ffmpeg没有视频编码器， 我怎么拿来用？

**Comment by bookzhan** [comment]
我发给你的那个编解码库是全的，没有精简的，x264也在里面，您可以试试

**Comment by wysaid** [comment]
你如果确定那个是全的， 你自己随便放一个可用的， 空白 libffmpeg.so 占位就可以了
比如你自己编译一个库， 名字叫 libffmpeg.so 就可以了

**Comment by bookzhan** [comment]
一个目录下只能放一个同名库,没法这么玩啊,我还是找替代方案吧,建议你开源吧,很多东西想用又被底层限制死了,更多的情况是需要根据你的这个进行二次开发
