### ISSUE TITLE
there is a file named "cgeEnlargeEyeFilter.h" missing in cgeImageFilterWrapper.cpp

### ISSUE THREAD

**Issue by jw20082009** [wysaid/android-gpuimage-plus#330]
there is a file named "cgeEnlargeEyeFilter.h" missing in cgeImageFilterWrapper.cpp
cgeImageFilterWrapper.cpp中缺失了一个叫做cgeEnlargeEyeFilter.h的头文件

**Comment by wysaid** [comment]
` cgeImageFilterWrapper.cpp` 这个文件目前版本已经删了, makefile里面没有用到~

**Comment by wysaid** [comment]
`cgeEnlargeEyeFilter.h` 这个文件如果需要可以在git 历史里面找到， 但是目前的代码里面用不到
