### ISSUE TITLE
大师兄有没有比较适合和这个库对接的硬编库推荐

### ISSUE THREAD

**Issue by jw20082009** [wysaid/android-gpuimage-plus#332]
大师兄有没有比较适合和这个库对接的硬编库推荐，因为在1280*720的时候，软编录制下来的视频在大部分机型上帧率下降的特别厉害，我想加进来

**Comment by wysaid** [comment]
可以试试看  https://github.com/google/grafika

**Comment by jw20082009** [comment]
@wysaid https://github.com/google/grafika 这个库里面讲的FBO方式，好像和当前库不一致，改起来会比较麻烦吧
