### ISSUE TITLE
想问下USE_GPU_I420_ENCODING这里为什么没有默认打开，是有什么问题吗

### ISSUE THREAD

**Issue by jw20082009** [wysaid/android-gpuimage-plus#334]
![qq 20180608213720](https://user-images.githubusercontent.com/8803478/41161126-451f80e8-6b64-11e8-955a-671006e69a8c.png)

想问下USE_GPU_I420_ENCODING这里为什么没有默认打开，是有什么问题吗

**Comment by wysaid** [comment]
之前是默认打开的， 然后有人提issue, 说在某些奇怪的视频尺寸下会出现黑边。 你这边如果不会支持任意尺寸， 仅适用预设好的尺寸的话可以打开
