### ISSUE TITLE
大师兄，录制出来的视频，有点视频、音频不同步的感觉，音频有点提前，视频有点滞后~~~

### ISSUE THREAD

**Issue by forgekxf** [wysaid/android-gpuimage-plus#34]

**Comment by wysaid** [comment]
应该没有这个问题， 你再检查下吧

**Comment by forgekxf** [comment]
确实存在那么一点点视音频不同步现象，视、音频合成时，能不能想办法调节一下呢~

**Comment by forgekxf** [comment]
大师兄，你看一下这个录制的视频，视音频不同步很明显：http://static.huajuanmall.com/user/video/1478872720.7893_5825ce90c0b65.mp4

**Comment by wysaid** [comment]
我这边从没遇到过啊， 会不会是你代码实现的问题， 你确定一下我放出来的demo有没有这个问题？
因为我这边也有产品化的东西， 经过测试没有你说的这个问题。

**Comment by forgekxf** [comment]
应该不是我这边代码实现的问题，平时录制出来的视频是这样的：http://static.huajuanmall.com/user/video/1477901299.9964_5816fbf3f3469.mp4  稍微有点音频提前，视频之后~~~

**Comment by wysaid** [comment]
能否使用repo里面自带的demo验证一下呢， 因为我这边没有遇到过这个问题， 我不确定是否真的存在这个问题， 而且这个问题我也不知道怎么去重现它

**Comment by forgekxf** [comment]
之前专门有使用repo里面的demo亲自录制过一段视频，确实有一点音频提前的问题~~~我在想能否在视音频合成的时候去进行一下调整吗

**Comment by wysaid** [comment]
你们有没有比较好的复现套路， 比如说用什么手机。
我写完这个之后专门测过的， 三星i9300, 魅族mx5等， 对着屏幕数一二三四， 口型都是对上的， 经过很多次测试， 应该是保证没问题的

**Comment by forgekxf** [comment]
我们公司里的三个测试机测试都存在这个问题，小米5，锤子1，还有一个华硕，全都是音频提前了那么一点点，说实话，如果不是有人提出来这个问题，我也一直没有发现~~~

**Comment by wysaid** [comment]
了解， 我会仔细研究下这个问题

**Comment by forgekxf** [comment]
大师兄，希望近期有时间能解决这个问题，多谢！！！

**Comment by forgekxf** [comment]
大师兄，看一下支付宝！

**Comment by forgekxf** [comment]
大师兄，我把录制出来的视频，使用mp4parser进行合并，最后得到的视频是不同步的，您能提供一下解决的思路吗？

**Comment by forgekxf** [comment]
您的工程没有存在视频不同步的问题！我已经确认过了！！！
