### ISSUE TITLE
Replace saved filter with new filter

### ISSUE THREAD

**Issue by evichrock** [wysaid/android-gpuimage-plus#347]
@wysaid Hi, I want this because after end recording with a filter and saved to file, I go to the review screen and I want to replace the filter (saved) with a new filter

**Comment by evichrock** [comment]
@wysaid Is it possible to have 2 frame recorders in CameraGLSurfaceViewWithTexture? I try to have 1 frame recorder (FR-A) applying selected filter and 1 frame recorder (FR-B) keep the origin (in AudioRecordRunnable I replace A with B then getAudioStreamtime cause crashing, so I back to FR-A), so at the end I end recording FR-A (shouldSave = false) and FR-B (shouldSave = true) but the saved file cannot open.

**Comment by wysaid** [comment]
You can do it much easier. Just modify the c++ part, record the frame before it applied the filters.

**Comment by wysaid** [comment]
Just move this line https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/interface/cgeFrameRecorder.cpp#L261
```
m_frameHandler->processingFilters();
```
to the end of the function.

**Comment by evichrock** [comment]
@wysaid ok I'll give it a try, thank you

**Comment by evichrock** [comment]
@wysaid Hi. I've experienced with 2 approaches, the first is use 2 frame recorders and it's working but i'm wondering there are any perf issues ?. The second is ur by moving m_frameHandler->processingFilters(); to the end of the function, it's working also but the prob is it's flashing while recording.
https://youtu.be/WJIHJyuUiDY
