### ISSUE TITLE
您好，如果要基于这个，做视频编辑应该如何实现，效率比较高

### ISSUE THREAD

**Issue by xufeifandj** [wysaid/android-gpuimage-plus#35]
录制完视频MP4，应该如何结合ffmpeg，进行后期的，贴动态图等标签，请教下。怎么样的方案速度才会快。

**Comment by wysaid** [comment]
demo里面带了一个加水印的例子， 你们可以参考下， 不过速度比较一般。
如果对速度要求比较高的话， 我也不大清楚~

**Comment by xufeifandj** [comment]
您好可以加个好友交流哈459821731
