### ISSUE TITLE
您好可以开放ceg 库吗

### ISSUE THREAD

**Issue by xufeifandj** [wysaid/android-gpuimage-plus#36]
现在想在编辑视频的时候，添加滤镜并且，保存滤镜到MP4，

**Comment by wysaid** [comment]
demo里面有例子， 现在已经支持

**Comment by xufeifandj** [comment]
貌似我试了还是不行，Simple Player Demo，Video Player Demo，添加完滤镜，没有应用到本地MP4

**Comment by wysaid** [comment]
编译代码里面的demo， 有个testcase

**Comment by wysaid** [comment]
播放器本来就没有保存的选项， 保存的时候离屏渲染

**Comment by xufeifandj** [comment]
您好，如果要将Mp4添加滤镜然后重新保存，怎么做才能保证性能

**Comment by wysaid** [comment]
离屏渲染那个代码是放出来的， 你也可以修改之后重新编译。
性能什么的估计还是要上硬编码， 结合ffmpeg速度不会太快

**Comment by xufeifandj** [comment]
你好，ffmpeg 终端指定好像没放出来。

**Comment by xufeifandj** [comment]
请教下，如何直接使用你这个项目里的ffmepg终端 
例如：
String togeler = String.format("ffmpeg -i %s -i %s %s",radio.getAbsolutePath(),ff.getAbsolutePath(),outputTempVideoPath);
								if (UtilityAdapter.FFmpegRun("",
										togeler) == 0) {

								}

**Comment by wysaid** [comment]
没有这个， 你可以自己编译出ffmpeg然后替换掉里面的 libffmepg.so
之后自己补充命令行模块

**Comment by xufeifandj** [comment]
那你原来封装的 ffmpeg 也得对上吧

**Comment by wysaid** [comment]
https://github.com/wysaid/FFmpeg-Android
我是依照这个来编译的， 当然， 删掉了很多用不到的模块
你只要保留H264, AAC 编解码， 基本上就ok.

**Comment by xufeifandj** [comment]
好的，你有email吗，有问题可以发你邮件哈

**Comment by wysaid** [comment]
admin@wysaid.org
或者直接这里留言也可以， 会自动转发邮件到我邮箱的。

**Comment by xufeifandj** [comment]
ok 谢了
