### ISSUE TITLE
请问下cgeGenerateVideoWithFilter 中的 传入参数，  mute是代码什么？

### ISSUE THREAD

**Issue by xufeifandj** [wysaid/android-gpuimage-plus#37]
cgeGenerateVideoWithFilter(const char* outputFilename, const char* inputFilename, const char* filterConfig, float filterIntensity, GLuint texID, CGETextureBlendMode blendMode, float blendIntensity, bool mute, CGETexLoadArg* loadArg)

filterConfig
filterIntensity
blendMode是代码什么
blendIntensity是代表什么
  mute
CGETexLoadArg

**Comment by wysaid** [comment]
blendMode名字在java代码里面有相应的体现， blendmode 的话， 你随便打开一个photoshop就能看见里面的图层叠加模式。
或者看这里： https://helpx.adobe.com/photoshop/using/blending-modes.html
以及这里: https://en.wikipedia.org/wiki/Blend_modes

**Comment by xufeifandj** [comment]
mute指的是什么

**Comment by wysaid** [comment]
大侠， 你查一下这个单词的意思就会知道， 这个单词的意思表示静音
true则静音
false则保持原生

**Comment by xufeifandj** [comment]
哥们 有个问题发你admin@wysaid.org邮箱了帮忙看看
