### ISSUE TITLE
build ffmpeg x86_64

### ISSUE THREAD

**Issue by NhatPham94** [wysaid/android-gpuimage-plus#373]
How can I build x86_64 ffmpeg.so file ? What version is your ffmpeg ? Could you give me any refs, thanks.

Nhat Pham,
Best regards

**Comment by AanalShah** [comment]
i had same issue , can any please build libCGE.so and libCGEExt.so file for architecture x86_64 , thanks

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/issues/451
