### ISSUE TITLE
Applying filters to existing videos

### ISSUE THREAD

**Issue by rajdeep1008** [wysaid/android-gpuimage-plus#379]
Hey @wysaid ,

I am trying to make a video editor app and showing selected video from memory to VideoPlayerGLSurfaceView and applying filters on that.

My question is, how should i go about saving the video in a new file with the selected filter applied.

Thanks

**Comment by wysaid** [comment]
See the simple test case

**Comment by rajdeep1008** [comment]
Thanks @wysaid
