### ISSUE TITLE
您好，请问下  handler.drawResult();videoPlayer.render();方法可以修改吗

### ISSUE THREAD

**Issue by xufeifandj** [wysaid/android-gpuimage-plus#38]
handler.setAsTarget();
                    glViewport(0, 0, videoPlayer.getLinesize(), videoHeight);
                    videoPlayer.render();
                    handler.processingFilters();

#if 1
                    glBindFramebuffer(GL_FRAMEBUFFER, 0);
                    glViewport(0, 0, videoWidth, videoHeight);
                    handler.drawResult();

**Comment by wysaid** [comment]
那个函数里面的东西都可以修改， 函数之外的比如handler和videoPlayer暂时不能修改， 因为是已经编译进so了

下个版本就都可以修改了， 我会把这部分的代码全都开源

**Comment by xufeifandj** [comment]
好的，我已经给你捐献了，等我发工资，我再给你捐献些哈谢了

**Comment by wysaid** [comment]
@xufeifandj  不用， 我还给你了。
觉得有用并且不缺钱才donate， 如果自己都没钱千万不要捐， 没必要的

**Comment by xufeifandj** [comment]
好人啊，那就谢了，等你开源哈，我先学习下你的代码，我多逛逛你博客

**Comment by wysaid** [comment]
😊
