### ISSUE TITLE
Face coordinates Issue

### ISSUE THREAD

**Issue by karticchaudhary** [wysaid/android-gpuimage-plus#395]
Scenario: 
ImageDeform Activity - When i touch the face, coordinates are like (x-40,y-50).
But when i try both the face tracker included in this library and google's face detection,
points i get are totally different. How can this be resolved ?

**Comment by wysaid** [comment]
Thanks, I'll fix it.

**Comment by karticchaudhary** [comment]
I resolved this issue. I have another issue,
In ImageDeformActivity, when bitmap is set on imageview on ui thread, setSurfaceCreatedCallback is called. But, when i perform certain things on bitmap in Asyntask and then set that bitmap to imageview, then setSurfaceCreatedCallback  is never called.

**Comment by wysaid** [comment]
Hi @karticchaudhary,

**Comment by karticchaudhary** [comment]
@wysaid anything on that above issue ?

**Comment by wysaid** [comment]
![image](https://user-images.githubusercontent.com/1430725/51426805-ca50ae00-1c2a-11e9-9cc9-518fbf0debdb.png)
You've deleted this line, so the bitmap is invalid.

**Comment by wysaid** [comment]
@karticchaudhary Just revert the line above.
