### ISSUE TITLE
你好运行新demo FaceTracker  无法识别或者很难识别

### ISSUE THREAD

**Issue by chongbo2013** [wysaid/android-gpuimage-plus#399]
你好运行新demo FaceTracker  无法识别或者很难识别

**Comment by wysaid** [comment]
不会吧， 近期修正过的才比较容易识别， 之前的版本有问题

**Comment by chongbo2013** [comment]
只有非常靠近，人脸才行哈，而且反回的顶点绘制缩放也出现了问题，可能跟那个缩放图像后，进行检测有关系，还有我手机分辨率1920*1080还有我将录制视频调整1280*720

**Comment by wysaid** [comment]
@chongbo2013  嗯， 这个是直接链接的开源的库， 本身效果不是特别好， 你可以把缩放改大一点， 对应的性能会降低很多.  如果是要产品化的东西， 人脸识别这块需要你们替换成别的更优的方案。

**Comment by chongbo2013** [comment]
![img_20190124_113207](https://user-images.githubusercontent.com/3191545/51652868-16ee0d80-1fcc-11e9-85e8-c26f170b0abc.jpg) 大师兄，我将 mBitmapDst.copyPixelsToBuffer(mImageCacheBuffer.position(0)); 图像绘制出来，是颠倒的，而且识别好像有问题你看看

**Comment by chongbo2013** [comment]
ok 谢谢

**Comment by chongbo2013** [comment]
![tim 20190124150951](https://user-images.githubusercontent.com/3191545/51660897-28dea900-1fea-11e9-9b3a-5def59d160e4.png)
我刚测试了，用这个方法可以识别，下面那个就识别不出

**Comment by chongbo2013** [comment]
大师兄 stmobile 这个库  是免费的吗 我看他没有 任何lience 验证

**Comment by wysaid** [comment]
> 大师兄 stmobile 这个库 是免费的吗 我看他没有 任何lience 验证

@chongbo2013 哪来的 stmobile, 我的repo里面没有哦, 这个应该是 sensetime 的sdk, 要么收费限制bundle id, 要么有时间限制的.
