### ISSUE TITLE
你好，最近在研究直播美白与磨皮效果

### ISSUE THREAD

**Issue by xxxhui** [wysaid/android-gpuimage-plus#4]
大神，有微博或者QQ么？

**Comment by wysaid** [comment]
admin@wysaid.org 有问题可以发邮件

**Comment by wysaid** [comment]
“ 怎么得到yuv数据， 怎么去渲染数据”
如果我没记错的话， 安卓版里面的java代码是放出来的， 你可以直接看

**Comment by wysaid** [comment]
已放出美颜效果， 请更新代码， camera demo第一个就是
