### ISSUE TITLE
ImageGLSurfaceView setFilterWithConfig not working

### ISSUE THREAD

**Issue by mym0404** [wysaid/android-gpuimage-plus#406]
I use ImageGLSurfaceView as camera preview view.

I get Camera byte array with setPreviewCallbackWithBuffer method, and convert NV21 -> RGB,
create bitmap and use setImageBitmap of ImageGLSurfaceView.

Although i used setFilterWithConfig with my custom filter, the preview result is not applied filter.

**Comment by Sp4Rx** [comment]
Are you trying to set the filter at on create? or on a button click?
