### ISSUE TITLE
on applying multiple filters the VideoPlayerGLSurfaceView and CameraRecordGLSurfaceView are getting slow.

### ISSUE THREAD

**Issue by rkkalkii** [wysaid/android-gpuimage-plus#408]
Hi, 
I have an issue with the speed of video which is getting slow on applying adjust filters and multiple filters on video and camera view of gpu. I am clueless of how to fix this. The video playing speed is very necessary to be normal.
Please help!

example of filter config i am applying is:
mPlayerView.setFilterWithConfig("@beautify bilateral 10.362694 3.5 2 @adjust sharpen 9.533679 1 @adjust shadowhighlight -2.590668 0 @adjust shadowhighlight 0 179.792725 @adjust level 0 1 1.000000 @vignette 0.300000 0.300000 @adjust colorbalance 0 0 0.192746 @adjust colorbalance 0 0.242487 0 @adjust brightness 0.500000 @adjust contrast 1.000000 @adjust saturation 2.000000 @adjust exposure 0.623558 "+@curve RGB(0,255)(255,0) @style cm mapping0.jpg 80 80 8 3 );

**Comment by wysaid** [comment]
It's too long to process.
Maybe you can simplify the rule string.
The `beautify bilateral` functions is very slow.

**Comment by wysaid** [comment]
If you're playing video, you can set a half-size of output, to achieve an acceleration.
And do saving with a full resolution.

**Comment by rkkalkii** [comment]
removing beautify bilateral and decreasing resolution of video view works for me,
thank you very much.

**Comment by rkkalkii** [comment]
removing beautify bilateral and decreasing resolution of video view works for me,
thank you very much.
