### ISSUE TITLE
半透明图片通过adjust滤镜处理后，得到的图片存在异常杂色

### ISSUE THREAD

**Issue by Dojane** [wysaid/android-gpuimage-plus#421]
![if_apple_2003193](https://user-images.githubusercontent.com/3959956/56860311-e7361380-69c7-11e9-9f3a-2e702a9e7e04.png)
![1556434999693](https://user-images.githubusercontent.com/3959956/56860313-eb623100-69c7-11e9-9e5e-36f133bfb295.png)

如图，小米4，系统android6.0.1，半透明图片通过adjust滤镜处理后,预览到的图片与实际保存到的图片不一致，边缘部分有杂色，调试时加载图片查看也是正常的，保存或直接canvas画图显示就出现异常杂色 ，求大师兄解惑。

**Comment by wysaid** [comment]
1. 首先本sdk并不保证带alpha通道的图片能在所有效果下正常
2. 输出的图片可能需要预乘一下, 具体做法就是所有通道值乘以alpha值.
你可以写一个自定义的filter, fsh里面的代码可能如下:
```
vec4 color = texture2D(inputImage, coord);
gl_FragColor = vec4(color.rgb * color.a, color.a);
```

**Comment by wysaid** [comment]
> 1. 首先本sdk并不保证带alpha通道的图片能在所有效果下正常
> 2. 输出的图片可能需要预乘一下, 具体做法就是所有通道值乘以alpha值.
>    你可以写一个自定义的filter, fsh里面的代码可能如下:
> 
> ```
> vec4 color = texture2D(inputImage, coord);
> gl_FragColor = vec4(color.rgb * color.a, color.a);
> ```

自定义的filter串到最后面跑一遍就行

**Comment by Dojane** [comment]
Thanks,我试下这个方法。

**Comment by Dojane** [comment]
谢谢哈！，可以解决这个问题。

**Comment by NiaNingXue** [comment]
遇到同样的问题，上面的兄弟能不能留个联系方式

**Comment by qianjujun** [comment]
> ![if_apple_2003193](https://user-images.githubusercontent.com/3959956/56860311-e7361380-69c7-11e9-9f3a-2e702a9e7e04.png) ![1556434999693](https://user-images.githubusercontent.com/3959956/56860313-eb623100-69c7-11e9-9e5e-36f133bfb295.png)
> 
> 如图，小米4，系统android6.0.1，半透明图片通过adjust滤镜处理后,预览到的图片与实际保存到的图片不一致，边缘部分有杂色，调试时加载图片查看也是正常的，保存或直接canvas画图显示就出现异常杂色 ，求大师兄解惑。

大佬，请教下 ，你这个这么解决的呢 ，我不知道怎么自定义滤镜rule，拼接到最后面，您能告诉我下吗
