### ISSUE TITLE
可以支持64位so吗

### ISSUE THREAD

**Issue by tianshaokai** [wysaid/android-gpuimage-plus#428]
1.如题

**Comment by wysaid** [comment]
读一下 https://github.com/wysaid/android-gpuimage-plus/blob/master/README.md

**Comment by tianshaokai** [comment]
谢谢 看到了，
compile 'org.wysaid:gpuimage-plus:2.6.1-armeabi'
compile 'org.wysaid:gpuimage-plus:2.6.1-armv7a'
compile 'org.wysaid:gpuimage-plus:2.6.1-armv8a'

这样是不是就可以了

**Comment by wysaid** [comment]
> 谢谢 看到了，
> compile 'org.wysaid:gpuimage-plus:2.6.1-armeabi'
> compile 'org.wysaid:gpuimage-plus:2.6.1-armv7a'
> compile 'org.wysaid:gpuimage-plus:2.6.1-armv8a'
> 
> 这样是不是就可以了

不是的, 只有 armv7a 是分出来的， 别的都在无后缀的那个版本里面
你们也可以自己打包自己想要的版本

**Comment by tianshaokai** [comment]
好的谢谢
