### ISSUE TITLE
Image Deform in real time

### ISSUE THREAD

**Issue by nhancv** [wysaid/android-gpuimage-plus#432]
Hi wysaid, 

Is there any way to deform a bitmap in real-time. I had checked ImageDeformActivity, but when I try with the camera which changes a preview bitmap in high fps, it does not work. Can you check, please?

**Comment by wysaid** [comment]
Sure you can.  But you should not use the bitmap.  You should pass the binary data, and change the OpenGL texture with `glTexSubImage2D`
