### ISSUE TITLE
音视频不同步问题的一点小灵感

### ISSUE THREAD

**Issue by bookzhan** [wysaid/android-gpuimage-plus#45]
最近在看你的源码, 我发现项目里面的帧率是int型, 但是有的手机帧率是动态的, 也就是说会有小数点, 这样精度会丢失,建议你把类型换成float试试

**Comment by wysaid** [comment]
帧率那个只是显示出来给开发者看的， 就是几行无关紧要的代码， 可以直接删掉的哦~
应该跟这个问题无关

**Comment by bookzhan** [comment]
在cgeVideoEncoder.cpp里面的addStream方法,你这样赋值了 c->time_base.den = frameRate;   然后在计算时间戳的时候你这么用了av_rescale_q(pkt.pts, codecCtx->time_base, m_context->pVideoStream->time_base) 这样就会导致有误差, 你可是试着找一个帧率不是整数的视频试一下

**Comment by wysaid** [comment]
这一段代码是FFPMEG官方文档里面的哦

**Comment by wysaid** [comment]
大概是这个位置：  https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/muxing.c

addStream 函数参考的这里的。  然后我参考的ffmpeg版本比较低， 几年前写的了。
我这个月会把这相关的全部开源， 到时候你可以自己试试看改一下哦

**Comment by bookzhan** [comment]
恩，感谢开源😊，官方的demo是有问题的，他这样会导致帧率永远是一个整数，我抽点时间把那一块改一下
