### ISSUE TITLE
ffmpeg libffmpeg_x86_64.so missing 

### ISSUE THREAD

**Issue by deepakrokz** [wysaid/android-gpuimage-plus#451]
Hi @wysaid ,

I hope you are doing well!
I know it's just a matter of some minutes for you create this FFmpeg .so file required, requesting you to please create this and include on priority so that builds can be pushed before the deadline of Feb.

Thanks in Advance.

**Comment by wysaid** [comment]
Sure

**Comment by deepakrokz** [comment]
Thanks for getting back @wysaid , when can I have it? it's urgent please try to understand and please help me.

**Comment by deepakrokz** [comment]
Also need to provide libCGE.so and libCGEExt.so as well for the same abi filter i.e. x86_64

**Comment by deepakrokz** [comment]
Hi @wysaid, 
I am eagerly waiting for your reply and also seeking for your help.

**Comment by deepakrokz** [comment]
Hi @wysaid , when can I expect this to be completed? Please let me know it's urgent for me

**Comment by deepakrokz** [comment]
@wysaid please reply.

**Comment by wysaid** [comment]
Sorry for the late reply. I'm on a short vacation.
I am trying solve this now.

**Comment by deepakrokz** [comment]
Thanks

**Comment by wysaid** [comment]
done:  https://github.com/wysaid/android-gpuimage-plus/tree/dev/master/library/src/main/libs/x86_64
Please try

**Comment by wysaid** [comment]
The build script is updated here: https://github.com/wysaid/FFmpeg-Android
The current ffmpeg version is 2.8.6
You can compile your own version with that.

**Comment by wysaid** [comment]
Merged to the latest commit, and support NDK 23
