### ISSUE TITLE
您好，我向在录制的时候输出mpegts格式.ts视频文件，好像无法修改

### ISSUE THREAD

**Issue by xufeifandj** [wysaid/android-gpuimage-plus#46]
avformat_alloc_output_context2(&ofmt_ctx, NULL,"mp4", out_filename);
您好，我向在录制的时候输出mpegts格式如何编码为.ts视频文件

**Comment by xufeifandj** [comment]
您好，录制出来的视频太大了 21秒优化 了 fps 和bit码率，依然很大，我向把录制直接编码成ts 格式，大量降低文件大小

**Comment by yeoggc** [comment]
@chongbo2013 您好请问你是怎么编码成ts格式？可以说下嘛？
