### ISSUE TITLE
录制的1080x1920的视频质量不如1080x1440的清晰

### ISSUE THREAD

**Issue by mafanwei** [wysaid/android-gpuimage-plus#476]
不知道发生了什么····还望解惑

**Comment by mafanwei** [comment]
导出本地视频文件，分辨率是对的，但是质量看起来就很糟糕，大片大片的马赛克，很像240p的视频

**Comment by wysaid** [comment]
码率设置的问题， demo 里面按 480p 设置的码率， 这块你需要改一下

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/blob/master/library/src/main/jni/interface/cgeVideoEncoder.cpp
这里改一下

**Comment by mafanwei** [comment]
c->bit_rate    = 64000;这个写死的是音频的比特率，视频的比特率是调用java的接口么

**Comment by wysaid** [comment]
可以啊， 你想办法把这个作为参数传进来就行了， java层可以设置。 改一下代码吧， 我这里就是写demo这么写的

> c->bit_rate = 64000;这个写死的是音频的比特率，视频的比特率是bitRate = 1650000，静态的话会导致视频文件过大，有办法做成动态比特率的么（VBR）

**Comment by mafanwei** [comment]
感谢您的帮助，已经完成了
