### ISSUE TITLE
视频转换质量问题

### ISSUE THREAD

**Issue by mafanwei** [wysaid/android-gpuimage-plus#477]
利用CGEFFmpegNativeLibrary.generateVideoWithFilter转换本地视频，输出质量变得非常差，原文件和输出文件大小接近10:1，如何保证原质量输出呢？

**Comment by mafanwei** [comment]
是因为cgeVideoUtils.cpp中，CGEVideoEncoderMP4的init函数中bitRate是写死的

**Comment by wysaid** [comment]
嗯， 你修改一下源代码， 把这个接口开放出去就行

**Comment by mafanwei** [comment]
这个我改了，重新编译了so，但是不知道怎么动态改CGEFrameRenderer中的DstSize，希望大佬可以指点一下
