### ISSUE TITLE
jcenter服务停止的对应

### ISSUE THREAD

**Issue by cuichanghao** [wysaid/android-gpuimage-plus#485]
jcenter服务将2022年2月要停止、请发布到别的repository
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

请问，有计划吗？

**Comment by wysaid** [comment]
有的， 实际上这个很好搭建, 比如这个： 
https://github.com/wysaid/android-gpuimage-plus-maven
你可以通过类似的方法自建服务， 然后用自己的服务
后续我把我自己创建的这个安卓的服务维护起来吧， 但是建议你们自己维护一个保持更新
