### ISSUE TITLE
Ui lags when calling method CGENativeLibrary.filterImage_MultipleEffects

### ISSUE THREAD

**Issue by Shibili-shibi** [wysaid/android-gpuimage-plus#496]
Iam using a imageview to load filtered bitmap.

Using method : Bitmap dstImage = CGENativeLibrary.filterImage_MultipleEffects(src, ruleString, 1.0f);

Using it in seekbar on progress changed and it lags.

Is there any way to apply filter smoothly when progress changed and apply to custom imageview

**Comment by wysaid** [comment]
You're not using the right function, the demo contains a image demo, please follow the instructions - not to read pixels and convert to bitmap, render the content directly
