### ISSUE TITLE
请问下能在这个基础上实现瘦脸 瘦腿效果嘛

### ISSUE THREAD

**Issue by luochen001** [wysaid/android-gpuimage-plus#499]
请问下能在这个基础上实现瘦脸 瘦腿效果嘛

**Comment by wysaid** [comment]
可以的， 参考我另一个仓库的用法:
- src: https://github.com/wysaid/wge
- 在线演示: http://wge.wysaid.org/webgl/demos/index.html

瘦脸的话， 用笔触液化可能不太能完全满足需求， 你需要一些关键点的准确位移+映射， 演示里面左边最下面几个就是。
