### ISSUE TITLE
你好！

### ISSUE THREAD

**Issue by chenjiuxu** [wysaid/android-gpuimage-plus#5]
我对视频录制添加滤镜对我非常有帮助！但现在你的源码没有这一部分的代码！能分享出来吗？？

**Comment by chenjiuxu** [comment]
请问有什么opengl es的书籍资料推选吗？？？

**Comment by wysaid** [comment]
好好把这个manual读一遍， 理解每个函数的意思比你看一半的教程有用 [khronos manual](https://www.khronos.org/opengles/sdk/docs/man/)

**Comment by wysaid** [comment]
已放出视频录制功能， 请更新
