### ISSUE TITLE
Support 16 KB page sizes

### ISSUE THREAD

**Issue by ozaneb** [wysaid/android-gpuimage-plus#536]
Android now supports 16KB page size and our native libraries should support it as well. Do you plan to update accordingly? 

https://developer.android.com/guide/practices/page-sizes#16-kb-impact

**Comment by wysaid** [comment]
Get,  I'll fix that.

**Comment by wysaid** [comment]
Supported.

**Comment by ozaneb** [comment]
@wysaid are you going to publish a new version for this improvement?

**Comment by wysaid** [comment]
> @wysaid are you going to publish a new version for this improvement?

No, upon reviewing publicly available information, I have discovered that enabling `16 KB page sizes` may lead to compatibility issues across various devices and system versions. Therefore, it is advisable for users to activate this feature based on their specific needs and to conduct their own testing.
