### ISSUE TITLE
你好编译FFmpeg-Android不知道为什么编译到一半报错了

### ISSUE THREAD

**Issue by xufeifandj** [wysaid/android-gpuimage-plus#55]
![qq 20161210175312](https://cloud.githubusercontent.com/assets/3191545/21072559/dffebbd0-bf01-11e6-9697-f759c4d02651.png)

**Comment by xufeifandj** [comment]
https://github.com/wysaid/FFmpeg-Android 按照你这个编译的

**Comment by wysaid** [comment]
这个……属于FFmpeg配置的问题， 我也不知道你什么情况， 反正我按着这个来是没问题的
