### ISSUE TITLE
你好，我直接运行你的demo，lib库有兼容问题

### ISSUE THREAD

**Issue by Toni-Toni** [wysaid/android-gpuimage-plus#57]
出问题手机为android 7.0系统：
targetSdkVersion 23时崩掉，dlopen failed .......,xx.so: has text relocations
targetSdkVersion 22警告:xx.so has text relocations. This is wasting memory and prevents security hardening. Please fix.

7.0以下貌似正常。

**Comment by wysaid** [comment]
你好， 代码里面已修复此问题， 你直接从代码运行就好
demo大概没及时更新

**Comment by Toni-Toni** [comment]
可以了，thx！
