### ISSUE TITLE
请问如何配合RecyclerView或者ListView使用

### ISSUE THREAD

**Issue by Doublemine** [wysaid/android-gpuimage-plus#58]
大师兄你好，我将ImageGLSurfaceView添加到RecyclerView中来预览不同的滤镜的效果时，滑动会有黑边，而且某些item可能是全黑的没有完成渲染，请问这是什么问题呢？

**Comment by wysaid** [comment]
这个我没试过呀， 一个ImageGLSurfaceView就能完成切换了， 而且只需要一份内存
如果你要存多个的话， 可以直接后台处理出Bitmap， 放到一般的ImageView上预览

**Comment by Doublemine** [comment]
@wysaid 谢谢大师兄回复。请问ImageGLSurfaceView生成Bitmap可以直接返回而不使用Callback吗？

**Comment by wysaid** [comment]
ImageGLSurfaceView生成的话是不行的， 你可以看看代码， 必须在glsurfaceview的线程跑才能拿到图片， 而你调用显然实在主线程。callback回调时也是在gl线程的。
你如果要后台生成图片， 看看 NativeLibrary里面的 "filterimage_*" 两个方法， 可以直接从Bitmap离屏渲染滤镜

**Comment by Doublemine** [comment]
好的，我去看看，谢谢大师兄耐心讲解
