### ISSUE TITLE
结束录制视频endRecording(bool shouldSave)

### ISSUE THREAD

**Issue by lwanghaol** [wysaid/android-gpuimage-plus#59]
结束录制视频endRecording(bool shouldSave)，其中参数shouldSave为是否保存视频，现在是录制好了后，再保存的，此时保存会有长时间的等待时间。能否将参数放到startRecording方法中呢，边录制边保存呢。

**Comment by wysaid** [comment]
噗， 你的思路很清奇……  你认为录制好之后再保存可能吗…… 你内存有多大？
不保存这个， 只是放弃写入文件尾， 导致这个视频不是一个完整视频无法播放， 实际上以及写入硬盘了， 建议好好看看代码， 以及自己观察下文件不管你传什么参数， 是否已经存在。
如果选保存， 会有等待是因为视频会等待缓存的数帧全部写完并写入文件尾。
这里写得比较简单， 直接阻塞GL线程等待的， 你可以改写相关逻辑， 使得在保存时画面继续更新
