### ISSUE TITLE
javacv库的问题

### ISSUE THREAD

**Issue by iceAnson** [wysaid/android-gpuimage-plus#6]
现在最新的javacv已经移动到了github，但是我从github编译出的so库并没有ffmpegInvoke和neno的so库，你的库代码应该是googlecode的；
github的库编译之后出现录制过程中会出现闪退的情况，请问你的库是怎么编译出来的

**Comment by wysaid** [comment]
本repo不需要javacv哦. 
带录制的版本使用的native ffmpeg 编写
