### ISSUE TITLE
请教下视频播放跳转的问题

### ISSUE THREAD

**Issue by Doublemine** [wysaid/android-gpuimage-plus#62]
大师兄你好，请问`VideoPlayerGLSurfaceView`在缓冲完成并且暂停状态要如何显示指定视频进度并显示该进度的画面帧呢？

**Comment by wysaid** [comment]
MediaPlayer 里面有个进度更新的listener啊， 可以得到进度。
你要跳转的话应该有个seek方法， seek过去就行。

**Comment by Doublemine** [comment]
@wysaid 感谢大师兄回复，这个方法我测试了在暂停状态下跳转`VideoPlayerGLSurfaceView`会黑屏而不会显示指定的进度的画面呢

**Comment by wysaid** [comment]
大概你需要处理下这个逻辑， 设置一个暂停标记， 然后让视频继续播放， 然后在 onDrawFrame 里面更新一帧之后再暂停。
或者用聪明一点的办法， queueEvent 然后在里面更新一下画面， 之后 post一个render request

**Comment by Doublemine** [comment]
好的，谢谢大师兄提醒，我去试试。另外还有一个问题是:我在将本地视频应用滤镜并保存的时候日志打印:`cgeExt: Error encoding audio frame: Invalid argument` 然后渲染出来的视频就木有声音了～请问下这个对视频的格式有什么要求吗？

**Comment by wysaid** [comment]
测试demo应该是没问题的对吧。 你检查下是不是音频编码不支持， 我编译的ffmpeg， 为了让ffmpeg.so 文件尽量小所以减少了很多东西， 音频应该是支持 aac 编码的。 你那个视频的音频编码如果不支持的话， 你可以重新编译一个完整的ffmpeg或者换个视频音频编码试试

**Comment by Doublemine** [comment]
嗯，应该就是ffmpeg音频支持的问题了，那个视频是Google photo自动给我生成的，其他视频没有问题。感谢大师兄解答～

**Comment by Doublemine** [comment]
@wysaid 请问下大师兄，还是视频滤镜的问题，我在应用视频滤镜保存时候，在小米4手机录制的视频出现了以下错误:

```
E/cgeExt: avcodec_encode_video2 error...
E/cgeExt: record frame failed!
E/libCGE: After "glDrawArrays" glGetError invalid framebuffer operation(0x506) at /Users/wysaid/work/bitbucket/cge-android/library/src/main/jni/src/common/cgeImageFilter.cpp:229
E/libCGE: CGEImageHandler::setAsTarget failed!
```
然后渲染出来的视频就只有声音没有画面了，请问也是ffmpeg 编码问题吗？

**Comment by wysaid** [comment]
啊， 就只是保存吗， 除了这个地方还有别的地方有错误吗， 以及这款手机的型号是啥？

**Comment by Doublemine** [comment]
@wysaid 目前只发现这个地方有问题，机型为小米手机4 系统为CM的6.0 非原生MIUI。。。另外在Nexue系原生Android手机上拍摄的短视频渲染视频是顺时针旋转了90度的。。@_@

**Comment by gzgang** [comment]
@Doublemine 请问 “在Nexue系原生Android手机上拍摄的短视频渲染视频是顺时针旋转了90度” 这个问题可有解呢，我也遇到了

**Comment by wysaid** [comment]
你们自己调试检查一下， 加以判断， 并设置一下旋转参数吧
我手头机型有限， 没有发现类似问题
