### ISSUE TITLE
录制视频问题

### ISSUE THREAD

**Issue by pengbs** [wysaid/android-gpuimage-plus#7]
你好，我下载demo的apk里面录制视频可以用，为什么到代码里面了录制视频的方法被屏蔽，没找到呢？

**Comment by wysaid** [comment]
你好, 安卓版的录制功能经过很长时间优化改进，比较具有竞争力(这个版本的视频录制无论从性能、稳定性、兼容性上好过多数市面上app， 例如 faceu 的安卓版)， 一旦直接放上来被很多公司使用的话会无形增加很多同类竞品， 利益相关，所以这里没有提供哦~
这个属于功能性的方法， 对于滤镜相关的学习并无助益， 如果确实需要这个功能， 请参考： https://github.com/google/grafika
这里有谷歌官方基于安卓 4.3 系统API的录制实现（看起来性能不高

**Comment by pengbs** [comment]
多谢你的回答，我们现在需求就是录制视频加滤镜，正好需要，希望大神能帮帮忙，万分感谢

**Comment by pengbs** [comment]
你好，你这个播放视频加滤镜也未开放了吗？

**Comment by wysaid** [comment]
开放了的， 你可以编译一个试试。

**Comment by pengbs** [comment]
谢谢回答，我使用提示nativeSetFilterWidthConfig这个ClassNotFound，自己编译没有jni文件呢？

**Comment by wysaid** [comment]
自己编译java部分， 自带的 libs 目录下的 so 文件里面是有的。

**Comment by pengbs** [comment]
我看你这最新的libs目录下没有ffmpeg.so文件，只有libCGE.so，导致处理视频时找不到相关jni方法

**Comment by wysaid** [comment]
不能处理视频哦， 只能播放视频。 可以在播放视频的时候加滤镜， 但是这里提供的版本并不能转储视频。
你需要自己实现以下转储功能哦~~ 可以参考 grafika

**Comment by xiemuyou** [comment]
您好!
您说"忽略jni源代码， jni源代码可在历史中查询， 之后版本均不提供源代码"
但是没有看到您说的历史版本,请问有什么方式可以找到吗?

**Comment by wysaid** [comment]
视频录制功能已放出， 请更新代码
