### ISSUE TITLE
GrayScale filter

### ISSUE THREAD

**Issue by cubatertech** [wysaid/android-gpuimage-plus#71]
Hi, Wysaid Team. 
Please let me know which one is GrayScale filter configuration, I want to use this.  Or let me know only Filter# according to CameraDemo Screen.
Thanks.

**Comment by wysaid** [comment]
There's a doc (https://github.com/wysaid/android-gpuimage-plus/wiki/Parsing-String-Rule)[https://github.com/wysaid/android-gpuimage-plus/wiki/Parsing-String-Rule] in Chinese.

I'm preparing to translate it into English.
You can refer to the monochrome filter or do it by yourself. The newest commit provides customized filter. You can write your own filter with shader code: (https://github.com/wysaid/android-gpuimage-plus/commit/66ce228653741180ea41c8dccdf512726980583b)[https://github.com/wysaid/android-gpuimage-plus/commit/66ce228653741180ea41c8dccdf512726980583b]

**Comment by cubatertech** [comment]
Thanks dear for your reply. I can check this.
