### ISSUE TITLE
大师兄jni编译失败

### ISSUE THREAD

**Issue by chongbo2013** [wysaid/android-gpuimage-plus#76]
The NDK dir is: D:/dev/android-sdk-windows/ndk-bundle, If the shell can not run
normally, you should set the NDK variable to your local ndk-dir
[armeabi] Install        : libCGE.so => libs/armeabi/libCGE.so
[armeabi] SharedLibrary  : libCGEExt.so
**D:/dev/android-sdk-windows/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.
9/include\ext/atomicity.h:49: error: undefined reference to '__atomic_fetch_add_
4'**
clang++.exe: error: linker command failed with exit code 1 (use -v to see invoca
tion)
make: *** [D:/gpuimage-new/android-gpuimage-plus/library/src/main/obj/local/arme
abi/libCGEExt.so] Error 1

**Comment by chongbo2013** [comment]
看了下不知道是不是 gcc问题

**Comment by wysaid** [comment]
这个……我没遇到过呀， 不好说， 你的NDK版本是多少呢，我上传的so使用的 r10e 这个版本编译的

**Comment by chongbo2013** [comment]
我的r13的哈哈

**Comment by chongbo2013** [comment]
我换个 10的看看 谢谢哈

**Comment by chongbo2013** [comment]
大师兄，我想将人脸识别结合到里面，cgeFrameRenderer.cpp  每一帧图像的数据是哪一个变量，应该在哪里处理 图像识别，可以帮忙指点下吗

**Comment by wysaid** [comment]
我看看这几周的时间状况， 把实时人脸识别加进去吧， 不过依旧使用内嵌的FaceTracker, 你们有接入第三方更快的sdk的话就自己改接口吧。

**Comment by wysaid** [comment]
估计这周不行， 下周可能有时间加进去

**Comment by chongbo2013** [comment]
好的 感谢哈。我自己先研究看看哈
