### ISSUE TITLE
opencv部分不完整，不方便添加方法

### ISSUE THREAD

**Issue by CodingPub** [wysaid/android-gpuimage-plus#82]
你好，请问这个项目使用的是哪个版本的OpenCV，是否修改过其中的方法？我能不能使用官网版本进行替换呢，需要实现图片合成视频的功能，希望通过OpenCV获取图片数据。

**Comment by wysaid** [comment]
可以的， opencv的头文件以及库文件都在jni目录， 你直接替换掉自己重新编译就行了

**Comment by CodingPub** [comment]
非常感谢你的神速回复，请问opencv的版本号还记得吗，我刚才下了2.x的最新版本替换，会报错

**Comment by wysaid** [comment]
我用的opencv3.1， 直接在官网下载预编译好的安卓版
[你下载这个的话应该没问题](https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.2.0/opencv-3.2.0-android-sdk.zip/download/)

**Comment by CodingPub** [comment]
好的，谢谢你 ^_^ 我试试看
