### ISSUE TITLE
自行编译FFmpeg无法应用视频滤镜

### ISSUE THREAD

**Issue by Doublemine** [wysaid/android-gpuimage-plus#84]
大师兄你好，我在尝试自行编译FFmpeg库并替换原本库中的ffmpeg，并重新编译之后。运行Demo中的`Camera Filter Demo`，点击`Recorded`弹出提示录制失败，同时打印如下log:
```shell
03-14 23:05:32.868 27367-6135/org.wysaid.cgedemo E/cgeExt: could not open file.
03-14 23:05:32.870 27367-6135/org.wysaid.cgedemo E/cgeExt: CGEFrameRecorder::startRecording - start recording failed!
03-14 23:05:32.870 27367-6135/org.wysaid.cgedemo E/wysaid: start recording failed!
```
同时`Test Cases`中的离屏视频渲染也无法正常使用，请问编译FFmpeg时需要开启什么我没有打开的参数吗？

FFmpeg版本为`FFmpeg 2.8.11 "Feynman"`
编译脚本地址https://github.com/DOORG/Android-FFmpeg-with-xH264-Build-Script

**Comment by lakmalz** [comment]
hey did you fixed this issue. How should i fixed this issue?

**Comment by wysaid** [comment]
Hei @lakmalz , please see this: https://github.com/wysaid/android-gpuimage-plus/issues/93
