### ISSUE TITLE
关于自己添加水印位置及大小方法

### ISSUE THREAD

**Issue by a785436663** [wysaid/android-gpuimage-plus#86]
大师兄，
我循着JNI方法里找
把"#unpack @krblend darken hehe.jpg 100"这个config
传到CGEFrameRenderer  setFilterWithConfig里
这个方法里调用了CGEMutipleEffectFilter  initWithEffectString方法
然后传到把CGEMutipleEffectFilter  的指针传到 m_frameHandler addImageFilter里 
initWithEffectString和addImageFilter方法我就只能在.h文件里找到声明
所以还是不知道怎么在JNI里添加一个方法可以去修改水印
我对JNI只是稍微了解

**Comment by wysaid** [comment]
范例里面应该有
https://github.com/wysaid/android-gpuimage-plus/tree/master/library/src/main/jni/source
参考自定义滤镜方法， 自己写一个贴水印的滤镜就完事

**Comment by a785436663** [comment]
好哒 谢谢

**Comment by a785436663** [comment]
大师兄，回答一下小菜鸡嘛，我上网查过这个错误，但是查不到，所以问一下你，主要核对一下你的环境 看看我这边是否版本问题，便以其他的JNI是正常的

**Comment by wysaid** [comment]
我编译这个用的ndk版本是r10e， 我不知道你用的啥版本， 但这个版本肯定没问题

**Comment by wysaid** [comment]
刚才更新了一下， 现在支持最新的r13b 了

**Comment by a785436663** [comment]
跟系统64位或者32位有没有关系  我使用cgywin+ndk编译的  你是在linux下么

**Comment by wysaid** [comment]
嗯， 我开虚拟机检查下

**Comment by wysaid** [comment]
![0000](https://cloud.githubusercontent.com/assets/1430725/24041018/a797b9a4-0b46-11e7-98c2-8d52f4e18638.jpg)

拿最新的win版r13b试了下， 没有任何问题， 应该是你自己的问题。

**Comment by wysaid** [comment]
win版的自己改一下buildJNI脚本里面的 ndk-build 为 ndk-build.cmd

**Comment by a785436663** [comment]
好的 谢谢大师兄 我研究一下

**Comment by Hellozhongxin** [comment]
@a785436663 您好，请问您实现了吗

**Comment by a785436663** [comment]
自己上水印效率慢 这个框架没有实现指定位置 但是你可以先把水印图片的bitmap处理一下
