### ISSUE TITLE
怎样支持ACV文件?

### ISSUE THREAD

**Issue by dengyuhan** [wysaid/android-gpuimage-plus#88]
如果要支持acv的话,是要把acv转换成glsl吗?
或者有没有更好的办法可以使用acv来调整曲线?

**Comment by wysaid** [comment]
项目首页有个工具， 直接用哪个工具调曲线， 然后保存就能看到对应的配置文件， 不需要acv

**Comment by wysaid** [comment]
如果一定要用ps， 可以参考[这个文档](https://github.com/wysaid/android-gpuimage-plus/wiki/Parsing-String-Rule)
看看曲线的格式， 不用保存acv， 直接把调节用到的关键点写成我这边定义的格式就行了， 效果一模一样
