### ISSUE TITLE
使用demo中的library后能调用ffmpeg命令吗

### ISSUE THREAD

**Issue by candrwow** [wysaid/android-gpuimage-plus#92]
大师兄，因为原项目使用了ffmpeg Android将视频转成图片,使用library后能否去掉ffmpeg Android? library能否单独实现ffmpeg命令呢。还有一个不太相关的问题哈，我使用系统api的mediaRecorder录制视频，录6秒视频会出现前后各丢失0.5秒左右的现象，最后视频只有5秒，好像是mediaRecorder.start stop方法延迟很大。该demo是如何解决这个问题的呢

**Comment by wysaid** [comment]
demo里面用到的ffmpeg不带命令功能， 你可以自己重新编译一份支持的，替换掉里面的。
mediaRecorder我在这里面没有用到， 所以不知道如何解决~
