### ISSUE TITLE
大师兄能把那编译ffmpeg的脚本提供一下吗

### ISSUE THREAD

**Issue by bookzhan** [wysaid/android-gpuimage-plus#93]
我用自己编译的ffmpeg库替换后,发现avcodec_encode_video2函数平均时间在40毫秒, 而用你的库时间在几毫秒, 其中也采用neno,但是效果不理想,不知道是哪儿出问题了. bookzhan@foxmail.com 谢谢

**Comment by wysaid** [comment]
https://github.com/wysaid/FFmpeg-Android

**Comment by yeoggc** [comment]
wysaid/FFmpeg-Android上的FFmpeg不能正常编译，x264相关的checkout不下来，能看看什么原因吗？

**Comment by wysaid** [comment]
用这个吧： http://git.videolan.org/git/x264.git

**Comment by yeoggc** [comment]
我用您给x264.git下载到FFmpeg-Android下，再运行FFmpeg-Android.sh，会报错 FFmpeg-Android/x264: No such file or directory

**Comment by wysaid** [comment]
脚本里面肯定有个下载 x264 的git链接， 你直接用上面的替换掉脚本里面的x264链接， 然后再运行呀

**Comment by yeoggc** [comment]
我按照你说的重新试了下，遇到这情况：
make-standalone-toolchain.sh used to install a new toolchain into an existing
directory. This is not desirable, as it will not clean up any stale files. If
you wish to remove the install directory before creation, pass --force.
./FFmpeg-Android.sh: line 145: pushd: /Users/guanguocheng/Dev/DevProject/StudyProject2/new1/FFmpeg-Android/x264: No such file or directory
buiding x264 to /Users/guanguocheng/Dev/DevProject/StudyProject2/new1/FFmpeg-Android/build/x264/armv7
./FFmpeg-Android.sh: line 150: ./configure: No such file or directory
cp: config.*: No such file or directory

**Comment by yeoggc** [comment]
我是用最新的NDK的，不知道有没影响？

**Comment by wysaid** [comment]
这……我也有点搞不清楚， 我用的时候没这问题， 直接搞定了

**Comment by yeoggc** [comment]
我直接编译FFmpeg，不用x264，替换掉之前的ffmpeg，应该没问题的吧？

**Comment by wysaid** [comment]
不行的， 这样是没法录视频的

**Comment by yeoggc** [comment]
这样啊，那您有没现成编译好的so库？直接发我？

**Comment by wysaid** [comment]
不是就在repo里面吗。。。

**Comment by yeoggc** [comment]
我是个菜鸟，问下repo在哪里可以找到？

**Comment by wysaid** [comment]
被你替换掉的

**Comment by yeoggc** [comment]
替换掉的那个是不能执行ffmpeg命令，我想根据https://github.com/wysaid/FFmpeg-Android提供的重新编译一份可以执行ffmpeg命令的so库

**Comment by wysaid** [comment]
嗯， 了解了， 这个其实你可以网上找吧， 之后替换掉就行了

**Comment by yeoggc** [comment]
我用最新版ffmpeg编译过并替换，发现您的ffmpeg库有的方法，最新版ffmpeg的没有，所以只能找ffmpeg对应的版本来编译了

**Comment by wysaid** [comment]
应该跟ffmpeg版本没关系， ffmpeg有很多模块， 可能你编译的版本少了某些必要的模块

**Comment by yeoggc** [comment]
行我在仔细研究看，有不懂，只能在打扰你了

**Comment by wysaid** [comment]
嗯， 我倒是有个支持命令行的版本， 不过很多功能不支持， 只有简单的视频抽帧什么的，你先自己试试看吧

**Comment by yeoggc** [comment]
我刚才试了下只编译ffmpeg无h264，替换后，测试了下是正常运行的

**Comment by wysaid** [comment]
666，
那你先试试看吧， 有问题了再说

**Comment by yeoggc** [comment]
请问项目上so文件是用NDK哪个版本编译的？

**Comment by yeoggc** [comment]
还有ffmpeg的版本是多少？

**Comment by bookzhan** [comment]
这个脚本是不能直接运行的,是要修改的,我改了一下,亲测可用https://github.com/bookzhan/FFmpeg-Android-build.git

**Comment by wysaid** [comment]
厉害~
项目上的用的 ndk-r10e
但是我测试过最新的ndk-r13b也没问题

**Comment by bookzhan** [comment]
我把 把ffmpeg 切换成3.2.4 x264切换成最新的，亲测可用https://github.com/bookzhan/FFmpeg-Android-build.git欢迎使用

**Comment by bookzhan** [comment]
@wysaid 大神，你才是厉害，最近在学你的代码，打算逐步实现你的所写的功能，就算是学习了，还望多指教

**Comment by wysaid** [comment]
😋

**Comment by yeoggc** [comment]
问个小问题，armv7是不是就是armeabi-v7a??

**Comment by yeoggc** [comment]
@bookzhan 问个小问题，armv7是不是就是armeabi-v7a??

**Comment by yeoggc** [comment]
@bookzhan 您编译出来的ffmpeg包含h264的吗？

**Comment by yeoggc** [comment]
@bookzhan 我用您编译的ffmpeg库替换项目中的，程序闪退并报以下异常java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "avcodec_alloc_frame" referenced by "libCGEExt.so"...。

**Comment by bookzhan** [comment]
armv7是一个系列是向下兼容的，比如兼容v7a，v7r，v7m什么的，具体我也不太懂，你可以去查一下。库是包含h264的，现在库用的是FFmpeg3.2.4，而大师兄的项目采用的是2.1.2的FFmpeg所以api是不一样的，不过我也编译了一个2.1.2版本的，这个就需要你把仓库git下来，然后检出2.1.2的那个版本

**Comment by yeoggc** [comment]
@bookzhan 我已经把你的仓库git下来了，我对git操作不太熟，具体怎么检出2.1.1版本，有点急，麻烦尽快回复谢谢了。

**Comment by bookzhan** [comment]
@yeoggc git checkout 08214393daa0eeea5ca6d5aff1b149af48c8dd11   这个版本就是2.1.2的，build目录下就是已经编译好的，你从新运./FFmpeg-Android.sh所有的都就切换过来了

**Comment by yeoggc** [comment]
谢了，问下这个可以执行ffmpeg命令？

**Comment by yeoggc** [comment]
@bookzhan 谢了，这个可以执行ffMpeg命令

**Comment by yeoggc** [comment]
@bookzhan 我费了好大的精力就是用能执行ffmpeg命令so库想替换掉原来的，搞了几天都不行，郁闷中

**Comment by bookzhan** [comment]
@yeoggc 能用就行，为了减少库的大小，库的功能还是限制了不少，你可以调整enable和disable来放开和关闭一些功能，如果有些FFmpeg命名不能执行的话，特别是有一个disable everthing

**Comment by yeoggc** [comment]
@bookzhan 因为我实现视频录制功能，需要转格式，分段录制，音视频合并等，所以需要用到ffmpeg命令，您有啥好建议嘛

**Comment by bookzhan** [comment]
@yeoggc 用ffmpeg命令不是好办法，你控制不了流程，建议用代码实现

**Comment by yeoggc** [comment]
代码实现，你是说用C还是Java？

**Comment by bookzhan** [comment]
c/c++
