### ISSUE TITLE
Filter is gone on onResume()

### ISSUE THREAD

**Issue by enginebai** [wysaid/android-gpuimage-plus#98]
When I apply the filter to the video with `setFilterWithConfig()` and the app goes to background and returns, the filter is gone.

Is there any way to keep the filter during the app lifecycle (`onPause()` -> `onResume()`)?

**Comment by wysaid** [comment]
Yeah, you can do that yourself.
Just keep the config string and the using intensity value, and pass it to the view again after "onSurfaceCreated"

**Comment by enginebai** [comment]
I just find a workaround to fix that:

```java
@Override
public void onResume() {
	super.onResume();
	mVideoBlur.onResume();
	if (mVideoBlur.getVisibility() == View.VISIBLE && mMessage != null)
		mVideoBlur.setVideoUri(Uri.parse(mMessage.getMedia().getUrl()),
				mPreparedCallback, mPlayCompletionCallback);
}
```

Here `mVideoBlur` is `VideoPlayerGLSurfaceView`. 
Is it a good way?

**Comment by wysaid** [comment]
I can't see any about filter.
You can add some logs to see if the `setFilterWithConfig()` is called after `onSurfaceCreated` when turn back from background

**Comment by enginebai** [comment]
I mean that my workaround worked anyway. I apply `setFilterWithConfig()` in my `mPreparedCallback`.

**Comment by wysaid** [comment]
Aha, that's OK~

**Comment by enginebai** [comment]
Thanks for your kindly help.
